StringTable {
 ItemClassName "DefaultStringTableItem"
 Items {
  DefaultStringTableItem "{AB29C0FFEE29AD03}" {
   Id "RK29-Item_M150RCO_Description"
   Target_en_us "4x32 RCO on the MK153 rail, graduated 100-500 m. The elevation is zeroed for HEAA."
  }
  DefaultStringTableItem "{AB29C0FFEE29AD02}" {
   Id "RK29-Item_M150RCO_Name"
   Target_en_us "M150 RCO (MK153)"
  }
  DefaultStringTableItem "{AB29C0FFEE29AD01}" {
   Id "RK29-Item_M7RCO_Description"
   Target_en_us "4x32 RCO on the MK153 rail, graduated 100-500 m. The elevation is zeroed for HEAA."
  }
  DefaultStringTableItem "{6A548019F1C5C92A}" {
   Id "RK29-Item_M7RCO_Name"
   Target_en_us "M7 RCO (MK153)"
  }
  DefaultStringTableItem "{AB29C0FFEE29AD05}" {
   Id "RK29-Item_MBUSFront_Description"
   Target_en_us "Folding front sight, deployed by default."
  }
  DefaultStringTableItem "{AB29C0FFEE29AD04}" {
   Id "RK29-Item_MBUSFront_Name"
   Target_en_us "MBUS Front (MK153)"
  }
 }
}