RK29_KitComposition {
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C09A}" {
   m_eSource MAG_PRIMARY
   m_iCount 3
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C09B}" {
   m_eSource ALIAS
   m_sAlias "frag"
   m_iCount 3
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C09C}" {
   m_eSource ALIAS
   m_sAlias "smoke"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C09D}" {
   m_eSource ALIAS
   m_sAlias "bayonet"
   m_bOnlyIfPrimaryTakesIt 1
  }
 }
 m_aWeapons {
  RK29_BlockWeaponEntry "{AB29C0FFEE29C09E}" {
   m_iSlotIndex 2
   m_sAlias "handgun"
  }
 }
}
