RK29_KitComposition : "{AB29C0FFEEB2000D}Configs/KitSystem/Kits/Common/infantry.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA06}" {
  Name "#AR-Role_Medic"
  Icon "{EE0B4CDEA86FC24A}UI/Textures/DeployMenu/LoadoutIcons/LoadoutIcons.imageset"
  IconSetName "EditableEntity_Character_Medic"
  m_aAuthoredLabels {
   ENTITYTYPE_CHARACTER ROLE_MEDIC
  }
 }
 m_aTraits +{
  MEDIC
 }
 m_aWeapons {
  RK29_WeaponGroupRef "{AB29C0FFEEB23317}" {
   m_sRef "assault_rifles"
  }
 }
 m_aClothing {
  RK29_ClothingGroupRef "{AB29C0FFEEB23318}" {
   m_sRef "vests_rifleman"
  }
 }
 m_aItems {
  RK29_ItemGroupRef "{AB29C0FFEEB23319}" {
   m_sRef "medic_supplies"
  }
 }
 m_aOverrides {
  RK29_OverrideRef "{AB29C0FFEEB23104}" {
   m_sOverride "no_etool"
  }
  RK29_Override "{AB29C0FFEEB22E18}" {
   m_sId "medic_bag"
   m_aSubstitute {
    RK29_OverrideSubstitute "{AB29C0FFEEB22E19}" {
     m_sTarget "back"
     m_sReplaceWith "back_medic"
    }
   }
  }
 }
}
