RK29_KitComposition : "{AB29C0FFEEB2000D}Configs/KitSystem/Kits/Common/infantry.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA07}" {
  Name "#AR-Role_HelicopterCrew"
  Icon "{EE0B4CDEA86FC24A}UI/Textures/DeployMenu/LoadoutIcons/LoadoutIcons.imageset"
  IconSetName "EditableEntity_Character_Helicopter_Crew"
  m_aAuthoredLabels {
   ENTITYTYPE_CHARACTER TRAIT_HELI_CREW
  }
 }
 m_aTraits +{
  VEHICLE_CREW
 }
 m_aWeapons {
  RK29_WeaponGroupRef "{AB29C0FFEEB2331A}" {
   m_sRef "carbines"
  }
 }
 m_aClothing {
  RK29_ClothingGroupRef "{AB29C0FFEEB2331B}" {
   m_sRef "vests_crew"
  }
 }
 m_aItems {
  RK29_ItemGroupRef "{AB29C0FFEEB2331C}" {
   m_sRef "crew_tools"
  }
 }
 m_aOverrides {
  RK29_OverrideRef "{AB29C0FFEEB23105}" {
   m_sOverride "no_etool"
  }
  RK29_OverrideRef "{AB29C0FFEEB23106}" {
   m_sOverride "reduced_rifle_ammo"
  }
  RK29_OverrideRef "{AB29C0FFEEB2A311}" {
   m_sOverride "no_nightvision"
  }
 }
}
