RK29_KitComposition : "{AB29C0FFEEB2000D}Configs/KitSystem/Kits/Common/infantry.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA0B}" {
  Icon "{EE0B4CDEA86FC24A}UI/Textures/DeployMenu/LoadoutIcons/LoadoutIcons.imageset"
  Name "Sniper"
  IconSetName "EditableEntity_Character_Sharpshooter"
  m_aAuthoredLabels {
   ENTITYTYPE_CHARACTER TRAIT_OPTICS ROLE_SHARPSHOOTER
  }
 }
 m_aWeapons {
  RK29_WeaponGroup "{AB29C0FFEEB21213}" {
   m_sId "sniper_rifles"
   m_sDisplayName "Rifle"
   m_aEntries {
    RK29_EntryWeapon "{AB29C0FFEEB21214}" {
     m_sWeapon "m40"
     m_bDefault 1
     m_aFactionKeys {
      "US"
     }
    }
    RK29_EntryWeapon "{AB29C0FFEEB21215}" {
     m_sWeapon "svd_api"
     m_bDefault 1
     m_aFactionKeys {
      "USSR"
     }
    }
   }
  }
 }
 m_aClothing {
  RK29_ClothingGroupRef "{AB29C0FFEEB2331F}" {
   m_sRef "vests_marksman"
  }
 }
 m_aOverrides {
  RK29_OverrideRef "{AB29C0FFEEB23109}" {
   m_sOverride "no_etool"
  }
  RK29_OverrideRef "{AB29C0FFEEB2310A}" {
   m_sOverride "colored_smoke_grenades"
  }
  RK29_OverrideRef "{AB29C0FFEEB2A312}" {
   m_sOverride "no_nightvision"
  }
  RK29_Override "{AB29C0FFEEB21216}" {
   m_sId "sniper_tweaks"
   m_aAdjust {
    RK29_OverrideAdjust "{AB29C0FFEEB21217}" {
     m_sTarget "sidearm_ammo/mag"
     m_iDefault 3
    }
   }
  }
 }
}
