RK29_KitComposition : "{AB29C0FFEE29B00A}Configs/KitSystem/Kits/Common/infantry.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA0C}" {
  Icon "{EE0B4CDEA86FC24A}UI/Textures/DeployMenu/LoadoutIcons/LoadoutIcons.imageset"
  Name "#AR-Role_CombatEngineer"
  IconSetName "EditableEntity_Character_Sapper"
  m_aAuthoredLabels {
   ENTITYTYPE_CHARACTER TRAIT_EXPLOSIVE ROLE_SAPPER
  }
 }
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C6D2}" {
   m_sBlock "{AB29C0FFEE29B111}Configs/KitSystem/Blocks/Common/grenades.conf"
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C567}" {
   m_eSource ALIAS
   m_sAlias "etool"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C568}" {
   m_eSource ALIAS
   m_sAlias "demo_block"
   m_iCount 4
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C569}" {
   m_eSource ALIAS
   m_sAlias "detonator"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C23F}" {
   m_sSlot "Back"
   m_sAlias "backpack_large"
  }
 }
 m_aTraits +{
  SAPPER
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C6E3}" {
   m_iSlot 1
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C6E4}" {
     m_sWeapon "mine_at"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C6E5}" {
       m_sAlias "mine_at"
       m_iCount 1
      }
     }
    }
   }
  }
 }
}
