RK29_KitComposition : "{AB29C0FFEE29B00A}Configs/KitSystem/Kits/Common/infantry.conf" {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C605}" {
   m_sBlock "{AB29C0FFEE29B00B}Configs/KitSystem/Blocks/Common/medic_items.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C606}" {
   m_sSlot "Back"
   m_sAlias "backpack_medic"
  }
 }
 m_aTraits +{
  MEDIC
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C607}" {
   m_iSlot 2
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C608}" {
     m_sWeapon "sidearm"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C609}" {
       m_iCount 2
      }
     }
    }
   }
  }
 }
}
