RK29_KitComposition : "{AB29C0FFEE29B00A}Configs/KitSystem/Kits/Common/infantry.conf" {
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C550}" {
   m_eSource ALIAS
   m_sAlias "etool"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C449}" {
   m_iSlot 2
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C448}" {
     m_sWeapon "sidearm"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3AF}" {
       m_iCount 2
      }
     }
    }
   }
  }
 }
}
