RK29_KitComposition : "{AB29C0FFEE29B00A}Configs/KitSystem/Kits/Common/infantry.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA05}" {
  Name "#AR-Role_AutomaticRifleman"
  Icon "{EE0B4CDEA86FC24A}UI/Textures/DeployMenu/LoadoutIcons/LoadoutIcons.imageset"
  IconSetName "EditableEntity_Character_Machinegunner"
  m_aAuthoredLabels {
   ENTITYTYPE_CHARACTER TRAIT_SUPPRESSIVE ROLE_MACHINEGUNNER
  }
 }
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C6D6}" {
   m_sBlock "{AB29C0FFEE29B111}Configs/KitSystem/Blocks/Common/grenades.conf"
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C554}" {
   m_eSource ALIAS
   m_sAlias "etool"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C6CD}" {
   m_sSlot "Back"
   m_sAlias "backpack"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C447}" {
   m_iSlot 2
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C446}" {
     m_sWeapon "sidearm"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3AE}" {
       m_iCount 2
      }
     }
    }
   }
  }
 }
}
