RK29_KitComposition : "{AB29C0FFEEB2000D}Configs/KitSystem/Kits/Common/infantry.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA05}" {
  Name "#AR-Role_AutomaticRifleman"
  Icon "{EE0B4CDEA86FC24A}UI/Textures/DeployMenu/LoadoutIcons/LoadoutIcons.imageset"
  IconSetName "EditableEntity_Character_Machinegunner"
  m_aAuthoredLabels {
   ENTITYTYPE_CHARACTER TRAIT_SUPPRESSIVE ROLE_MACHINEGUNNER
  }
 }
 m_aExclusions {
  RK29_Exclusion "{AB29C0FFEEB22F80}" {
   m_sWhen "machine_guns/pkmn"
   m_sBlock "vests_mg/harness_ar"
  }
  RK29_Exclusion "{AB29C0FFEEB22F81}" {
   m_sWhen "machine_guns/rpk74n"
   m_sBlock "vests_mg/harness_mg"
  }
 }
 m_aWeapons {
  RK29_WeaponGroup "{AB29C0FFEEB21218}" {
   m_sId "machine_guns"
   m_sDisplayName "Machine gun"
   m_aEntries {
    RK29_EntryWeapon "{AB29C0FFEEB21219}" {
     m_sWeapon "m249"
     m_aFactionKeys {
      "US"
     }
    }
    RK29_EntryWeapon "{AB29C0FFEEB2121A}" {
     m_sWeapon "m60"
     m_bDefault 1
     m_aFactionKeys {
      "US"
     }
    }
    RK29_EntryWeapon "{AB29C0FFEEB2121B}" {
     m_sWeapon "rpk74n"
     m_aFactionKeys {
      "USSR"
     }
    }
    RK29_EntryWeapon "{AB29C0FFEEB2121D}" {
     m_sWeapon "pkmn"
     m_bDefault 1
     m_aFactionKeys {
      "USSR"
     }
    }
   }
  }
 }
 m_aClothing {
  RK29_ClothingGroupRef "{AB29C0FFEEB2330C}" {
   m_sRef "vests_mg"
  }
 }
 m_aOverrides {
  RK29_Override "{AB29C0FFEEB22E39}" {
   m_sId "mg_pack"
   m_aAdjust {
    RK29_OverrideAdjust "{AB29C0FFEEB22E38}" {
     m_sTarget "back/alice_medium"
     m_bDefault 1
    }
    RK29_OverrideAdjust "{AB29C0FFEEB22E3D}" {
     m_sTarget "back/kolobok"
     m_bDefault 1
    }
   }
  }
 }
}
