RK29_KitComposition : "{AB29C0FFEEB2000D}Configs/KitSystem/Kits/Common/infantry.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA03}" {
  Icon "{EE0B4CDEA86FC24A}UI/Textures/DeployMenu/LoadoutIcons/LoadoutIcons.imageset"
  Name "#AR-Role_Grenadier"
  IconSetName "EditableEntity_Character_Grenadier"
  m_aAuthoredLabels {
   ENTITYTYPE_CHARACTER TRAIT_EXPLOSIVE ROLE_GRENADIER
  }
 }
 m_aWeapons {
  RK29_WeaponGroup "{AB29C0FFEEB2121F}" {
   m_sId "grenadier_rifles"
   m_sDisplayName "Rifle"
   m_aEntries {
    RK29_EntryWeapon "{AB29C0FFEEB21220}" {
     m_sWeapon "m16a2_m203"
     m_aFactionKeys {
      "US"
     }
    }
    RK29_EntryWeapon "{AB29C0FFEEB21221}" {
     m_sWeapon "m16a3_m203"
     m_bDefault 1
     m_aFactionKeys {
      "US"
     }
    }
    RK29_EntryWeapon "{AB29C0FFEEB21222}" {
     m_sWeapon "ak74n_gp25"
     m_bDefault 1
     m_aFactionKeys {
      "USSR"
     }
    }
   }
  }
 }
 m_aClothing {
  RK29_ClothingGroupRef "{AB29C0FFEEB23313}" {
   m_sRef "vests_gl"
  }
 }
}
