SCR_ConfigurableDialogUiPresets {
 m_aPresets {
  SCR_ConfigurableDialogUiPreset "{AB29C0FFEE296001}" {
   m_sTag "kitpicker"
   m_sTitle "SELECT KIT"
   m_sLayout "{604721ED8E6ED459}UI/layouts/Menus/Dialogs/ConfigurableDialog_Big.layout"
   m_sContentLayout "{AB29C0FFEE293000}UI/KitSystem/RK29_KitPicker.layout"
   m_aButtons {
    SCR_ConfigurableDialogUiButtonPreset "{AB29C0FFEE296003}" {
     m_sTag "confirm"
     m_sActionName "RK29_DialogApply"
     m_sLabel "Apply Kit"
     m_eAlign RIGHT
    }
    SCR_ConfigurableDialogUiButtonPreset "{AB29C0FFEE296002}" {
     m_sTag "cancel"
     m_sActionName "MenuBack"
     m_sLabel "Close"
    }
   }
  }
 }
}
