SCR_ConfigurableDialogUiPresets {
 m_aPresets {
  SCR_ConfigurableDialogUiPreset "{AB29C0FFEEB2153A}" {
   m_sTag "loadout"
   m_sTitle "LOADOUT"
   m_sLayout "{604721ED8E6ED459}UI/layouts/Menus/Dialogs/ConfigurableDialog_Big.layout"
   m_sActionContext "RK29_KitMenuContext"
   m_sContentLayout "{AB29C0FFEEB21520}UI/KitSystem/RK29_LoadoutMenu.layout"
   m_aButtons {
    SCR_ConfigurableDialogUiButtonPreset "{AB29C0FFEEB2153B}" {
     m_sTag "confirm"
     m_sActionName "RK29_DialogApply"
     m_sLabel "Apply Kit"
     m_eAlign RIGHT
    }
    SCR_ConfigurableDialogUiButtonPreset "{AB29C0FFEEB2153C}" {
     m_sTag "cancel"
     m_sActionName "MenuBack"
     m_sLabel "Close"
    }
   }
  }
 }
}
