RK29_KitBlock {
 m_aClothing {
  RK29_BlockClothingEntry "{AB29C0FFEE29C316}" {
   m_sSlot "Vest"
   m_sPrefab "{477A190AF2A17B8A}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_MG.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C317}" {
   m_sSlot "Back"
   m_sPrefab "{4805E67E2AE30F8D}Prefabs/Items/Equipment/Backpacks/Backpack_Medical_M5.et"
  }
 }
}
