RK29_KitBlock {
 m_aClothing {
  RK29_BlockClothingEntry "{AB29C0FFEE29C200}" {
   m_sSlot "Hat"
   m_sPrefab "{FE5C49069C2499D9}Prefabs/Characters/HeadGear/Helmet_PASGT_01/Helmet_PASGT_01_cover.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C201}" {
   m_sSlot "Jacket"
   m_sPrefab "{C7861F11D5334C0E}Prefabs/Characters/Uniforms/Jacket_US_BDU.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C202}" {
   m_sSlot "ArmoredVest"
   m_sPrefab "{725C5E1C75CADAF4}Prefabs/Characters/Vests/Vest_M69/Vest_M69_M81woodland.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C203}" {
   m_sSlot "Pants"
   m_sPrefab "{604BB72BE8E023C2}Prefabs/Characters/Uniforms/Pants_US_BDU.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C204}" {
   m_sSlot "Boots"
   m_sPrefab "{DAAFD15478BDE1C3}Prefabs/Characters/Footwear/CombatBoots_US_01.et"
  }
 }
 m_aEquipment {
  RK29_BlockClothingEntry "{AB29C0FFEE29C205}" {
   m_sSlot "BinocularSlot"
   m_sPrefab "{0CF54B9A85D8E0D4}Prefabs/Items/Equipment/Binoculars/Binoculars_M22/Binoculars_M22.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C206}" {
   m_sSlot "WristwatchSlot"
   m_sPrefab "{78ED4FEF62BBA728}Prefabs/Items/Equipment/Watches/Watch_SandY184A.et"
  }
 }
}
