RK29_KitBlock {
 m_aClothing {
  RK29_BlockClothingEntry "{AB29C0FFEE29C319}" {
   m_sSlot "Vest"
   m_sPrefab "{4711A4CAF64C4CEE}Prefabs/Characters/Vests/Vest_SovietHarness/Variants/Vest_SovietHarness_AR.et"
  }
 }
}
