RK29_KitBlock {
 m_aClothing {
  RK29_BlockClothingEntry "{AB29C0FFEE29C207}" {
   m_sSlot "Hat"
   m_sPrefab "{22963D69CA50EB9E}Prefabs/Characters/HeadGear/Helmet_SSh68_01/Helmet_SSh68_01_net.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C208}" {
   m_sSlot "Jacket"
   m_sPrefab "{ED9FFC8C35C98B8B}Prefabs/Characters/Uniforms/Jacket_M88_TTsKO.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C209}" {
   m_sSlot "ArmoredVest"
   m_sPrefab "{ADE19B33DCBB9005}Prefabs/Characters/Vests/Vest_6B2/Vest_6B2.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C20A}" {
   m_sSlot "Pants"
   m_sPrefab "{7E45E8E203507300}Prefabs/Characters/Uniforms/Pants_M88_TTsKO.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C20B}" {
   m_sSlot "Boots"
   m_sPrefab "{C7923961D7235D70}Prefabs/Characters/Footwear/CombatBoots_Soviet_01.et"
  }
 }
}
