RK29_WeaponCatalog {
 m_aWeapons {
  RK29_WeaponDef "{AB29C0FFEE29C300}" {
   m_sId "m249"
   m_sPrefab "{D2B48DEBEF38D7D7}Prefabs/Weapons/MachineGuns/M249/MG_M249.et"
   m_aAmmo {
    RK29_WeaponAmmoDef "{AB29C0FFEE29C301}" {
     m_sAlias "belt"
     m_sPrefab "{06D722FC2666EB83}Prefabs/Weapons/Magazines/Box_556x45_M249_200rnd_4Ball_1Tracer.et"
    }
   }
  }
  RK29_WeaponDef "{AB29C0FFEE29C302}" {
   m_sId "m60"
   m_sPrefab "{D182DCDD72BF7E34}Prefabs/Weapons/MachineGuns/M60/MG_M60.et"
   m_aAmmo {
    RK29_WeaponAmmoDef "{AB29C0FFEE29C303}" {
     m_sAlias "belt"
     m_sPrefab "{4D2C1E8F3A81F894}Prefabs/Weapons/Magazines/Box_762x51_M60_100rnd_4Ball_1Tracer.et"
    }
   }
  }
  RK29_WeaponDef "{AB29C0FFEE29C304}" {
   m_sId "rpk74"
   m_sPrefab "{A7AF84C6C58BA3E8}Prefabs/Weapons/MachineGuns/RPK74/MG_RPK74.et"
   m_aAmmo {
    RK29_WeaponAmmoDef "{AB29C0FFEE29C305}" {
     m_sAlias "mag"
     m_sPrefab "{D78C667F59829717}Prefabs/Weapons/Magazines/Magazine_545x39_RPK_45rnd_4Ball_1Tracer.et"
    }
   }
  }
  RK29_WeaponDef "{AB29C0FFEE29C306}" {
   m_sId "pkm"
   m_sPrefab "{A89BC9D55FFB4CD8}Prefabs/Weapons/MachineGuns/PKM/MG_PKM.et"
   m_aAmmo {
    RK29_WeaponAmmoDef "{AB29C0FFEE29C307}" {
     m_sAlias "belt"
     m_sPrefab "{E5E9C5897CF47F44}Prefabs/Weapons/Magazines/Box_762x54_PK_100rnd_4Ball_1Tracer.et"
    }
   }
  }
  RK29_WeaponDef "{AB29C0FFEE29C308}" {
   m_sId "m16a2_carbine"
   m_sPrefab "{F97A4AC994231900}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine.et"
   m_aAmmo {
    RK29_WeaponAmmoDef "{AB29C0FFEE29C309}" {
     m_sAlias "mag"
    }
   }
  }
  RK29_WeaponDef "{AB29C0FFEE29C30A}" {
   m_sId "ak74"
   m_sPrefab "{FA5C25BF66A53DCF}Prefabs/Weapons/Rifles/AK74/Rifle_AK74.et"
   m_aAmmo {
    RK29_WeaponAmmoDef "{AB29C0FFEE29C30B}" {
     m_sAlias "mag"
    }
   }
  }
  RK29_WeaponDef "{AB29C0FFEE29C30C}" {
   m_sId "m72"
   m_sPrefab "{9C5C20FB0E01E64F}Prefabs/Weapons/Launchers/M72/Launcher_M72A3.et"
   m_aAmmo {
    RK29_WeaponAmmoDef "{AB29C0FFEE29C30D}" {
     m_sAlias "rocket"
     m_sPrefab "{9C5C20FB0E01E64F}Prefabs/Weapons/Launchers/M72/Launcher_M72A3.et"
    }
   }
  }
  RK29_WeaponDef "{AB29C0FFEE29C30E}" {
   m_sId "rpg7"
   m_sPrefab "{7A82FE978603F137}Prefabs/Weapons/Launchers/RPG7/Launcher_RPG7.et"
   m_aAmmo {
    RK29_WeaponAmmoDef "{AB29C0FFEE29C30F}" {
     m_sAlias "rocket"
     m_sPrefab "{32E12D322E107F1C}Prefabs/Weapons/Ammo/Ammo_Rocket_PG7VM.et"
    }
   }
  }
  RK29_WeaponDef "{AB29C0FFEE29C420}" {
   m_sId "m16a3"
   m_sPrefab "{A96DAB072888B0A8}Prefabs/Weapons/Rifles/M16/29th_M16A3.et"
  }
  RK29_WeaponDef "{AB29C0FFEE29C421}" {
   m_sId "m16a3_m203"
   m_sPrefab "{AB29C0FFEE29D004}Prefabs/Weapons/Rifles/M16/29th_M16A3_M203_HE.et"
  }
  RK29_WeaponDef "{AB29C0FFEE29C422}" {
   m_sId "ak74n"
   m_sPrefab "{96DFD2E7E63B3386}Prefabs/Weapons/Rifles/AK74/Rifle_AK74N.et"
  }
  RK29_WeaponDef "{AB29C0FFEE29C423}" {
   m_sId "ak74n_gp25"
   m_sPrefab "{BC6C9476FB3219A7}Prefabs/Weapons/Rifles/AK74/Rifle_AK74N_GP25.et"
  }
  RK29_WeaponDef "{AB29C0FFEE29C424}" {
   m_sId "aks74un"
   m_sPrefab "{FA0E25CE35EE945F}Prefabs/Weapons/Rifles/AKS74U/Rifle_AKS74UN.et"
  }
  RK29_WeaponDef "{AB29C0FFEE29C425}" {
   m_sId "m21"
   m_sPrefab "{B31929F65F0D0279}Prefabs/Weapons/Rifles/M14/Rifle_M21.et"
  }
  RK29_WeaponDef "{AB29C0FFEE29C426}" {
   m_sId "m21_parade"
   m_sPrefab "{3FB5275A6505B323}Prefabs/Weapons/Rifles/M14/Rifle_M21_base.et"
  }
  RK29_WeaponDef "{AB29C0FFEE29C427}" {
   m_sId "svd"
   m_sPrefab "{3EB02CDAD5F23C82}Prefabs/Weapons/Rifles/SVD/Rifle_SVD.et"
  }
  RK29_WeaponDef "{AB29C0FFEE29C428}" {
   m_sId "sidearm"
   m_aPerFaction {
    RK29_WeaponFactionPrefab "{AB29C0FFEE29C429}" {
     m_sFactionKey "US"
     m_sPrefab "{1353C6EAD1DCFE43}Prefabs/Weapons/Handguns/M9/Handgun_M9.et"
    }
    RK29_WeaponFactionPrefab "{AB29C0FFEE29C42A}" {
     m_sFactionKey "USSR"
     m_sPrefab "{C0F7DD85A86B2900}Prefabs/Weapons/Handguns/PM/Handgun_PM.et"
    }
   }
  }
 }
}
