RK29_SquadKitCatalog {
 m_aSquads {
  RK29_SquadKits "{AB29C0FFEE2901A5}" {
   m_sGroupName "*"
   m_aKitNames {
    "29th US - Squad Leader" "29th US - Rifleman" "29th US - Machine Gunner" "29th US - Light Anti-Tank" "29th US - Grenadier" "29th US - Medic" "29th US - Combat Engineer" "29th US - Battle Rifle"
    "29th USSR - Squad Leader" "29th USSR - Rifleman" "29th USSR - Machine Gunner" "29th USSR - Light Anti-Tank" "29th USSR - Grenadier" "29th USSR - Medic" "29th USSR - Combat Engineer" "29th USSR - Battle Rifle"
   }
  }
  RK29_SquadKits "{AB29C0FFEE2901A1}" {
   m_sGroupName "29th Squad"
   m_aKitNames {
    "29th US - Squad Leader" "29th US - Rifleman" "29th US - Machine Gunner" "29th US - Light Anti-Tank" "29th US - Grenadier" "29th US - Medic" "29th US - Combat Engineer" "29th US - Battle Rifle"
    "29th USSR - Squad Leader" "29th USSR - Rifleman" "29th USSR - Machine Gunner" "29th USSR - Light Anti-Tank" "29th USSR - Grenadier" "29th USSR - Medic" "29th USSR - Combat Engineer" "29th USSR - Battle Rifle"
    "29th Parade"
   }
  }
  RK29_SquadKits "{AB29C0FFEE2901A2}" {
   m_sGroupName "29th Crew"
   m_aKitNames {
    "29th US - Crewman" "29th US - Pilot"
    "29th USSR - Crewman" "29th USSR - Pilot"
   }
  }
  RK29_SquadKits "{AB29C0FFEE2901A3}" {
   m_sGroupName "29th HQ"
   m_aKitNames {
    "29th US - Squad Leader" "29th US - Sniper" "29th US - Rifleman"
    "29th USSR - Squad Leader" "29th USSR - Sniper" "29th USSR - Rifleman"
    "29th Parade"
   }
  }
  RK29_SquadKits "{AB29C0FFEE2901A4}" {
   m_sGroupName "29th Training Platoon"
   m_aKitNames {
    "29th TP - Recruit" "29th TP - Training Staff"
   }
  }
 }
}
