RK29_MagazineSetCatalog {
 m_aMagazineSets {
  RK29_MagazineSet "{AB29C0FFEE290171}" {
   m_sMagazineWell "MagazineWellAK545"
   m_aVariants {
    RK29_MagVariant "{AB29C0FFEE290172}" {
     m_sName "ball"
     m_sPrefab "{63C1E699345B24F9}Prefabs/Weapons/Magazines/Magazine_545x39_AK_30rnd_Base.et"
    }
   }
  }
  RK29_MagazineSet "{AB29C0FFEE290173}" {
   m_sMagazineWell "MagazineWellM14"
   m_aVariants {
    RK29_MagVariant "{AB29C0FFEE290174}" {
     m_sName "ap"
     m_sPrefab "{C319540BC96AE9BB}Prefabs/Weapons/Magazines/Magazine_762x51_M14_20rnd_M61_AP.et"
    }
   }
  }
  RK29_MagazineSet "{AB29C0FFEE290175}" {
   m_sMagazineWell "MagazineWellSVD"
   m_aVariants {
    RK29_MagVariant "{AB29C0FFEE290176}" {
     m_sName "lps"
     m_sPrefab "{77595CB9F596E6AC}Prefabs/Weapons/Magazines/Magazine_762x54_SVD_10rnd_LPS.et"
    }
   }
  }
 }
}
