RK29_AttachmentCatalog {
 m_aAttachments {
  RK29_AttachmentDef "{AB29C0FFEEB21041}" {
   m_sId "bayonet_us"
   m_sPrefab "{558117556F3880A8}Prefabs/Weapons/Attachments/Bayonets/Bayonet_M9.et"
  }
  RK29_AttachmentDef "{AB29C0FFEEB22A00}" {
   m_sId "hider_a2"
   m_sPrefab "{6288A1F1A5E3AC37}Prefabs/Weapons/Attachments/Muzzle/FlashHider_M16A2/FlashHider_M16.et"
  }
  RK29_AttachmentDef "{AB29C0FFEEB22A01}" {
   m_sId "suppressor_m16"
   m_sPrefab "{E52C9791E1554A5F}Prefabs/Weapons/Attachments/Muzzle/Suppressor_M16/Suppressor_M16.et"
  }
  RK29_AttachmentDef "{AB29C0FFEEB22A02}" {
   m_sId "hider_ak74"
   m_sPrefab "{4A815EB8B824974A}Prefabs/Weapons/Attachments/Muzzle/FlashHider_AK74/FlashHider_AK74.et"
  }
  RK29_AttachmentDef "{AB29C0FFEEB22A03}" {
   m_sId "hider_aks74u"
   m_sPrefab "{06D4C36A6D585275}Prefabs/Weapons/Attachments/Muzzle/FlashHider_AKS74u/FlashHider_AKS74u.et"
  }
  RK29_AttachmentDef "{AB29C0FFEEB22A04}" {
   m_sId "suppressor_pbs4"
   m_sPrefab "{3B96FAC169E27037}Prefabs/Weapons/Attachments/Muzzle/Suppressor_PBS4/Suppressor_PBS4.et"
  }
  RK29_AttachmentDef "{AB29C0FFEEB21042}" {
   m_sId "bayonet_ussr"
   m_sPrefab "{98C79F5FAE12F9B6}Prefabs/Weapons/Attachments/Bayonets/Bayonet_6Kh4.et"
  }
  RK29_AttachmentDef "{AB29C0FFEEB21400}" {
   m_sId "ap2k"
   m_sPrefab "{08286DDBB1F33FF1}Prefabs/Weapons/Attachments/Optics/Optic_AP2k/Collim_AP2k.et"
  }
  RK29_AttachmentDef "{AB29C0FFEEB21401}" {
   m_sId "4x20"
   m_sPrefab "{BD496EE1B40DC510}Prefabs/Weapons/Attachments/Optics/Optic_4x20/Optic_4x20.et"
   m_bMagnified 1
  }
  RK29_AttachmentDef "{AB29C0FFEEB21402}" {
   m_sId "1p63"
   m_sPrefab "{FE2896D202FE7449}Prefabs/Weapons/Attachments/Optics/1p63/Optic_1P63.et"
  }
  RK29_AttachmentDef "{AB29C0FFEEB21403}" {
   m_sId "1p78"
   m_sPrefab "{8D4BAA235F7EDBEA}Prefabs/Weapons/Attachments/Optics/1p78/Optic_1P78.et"
   m_bMagnified 1
  }
  RK29_AttachmentDef "{AB29C0FFEEB21404}" {
   m_sId "1p29"
   m_sPrefab "{ACDF49FACD0701A8}Prefabs/Weapons/Attachments/Optics/Optic_1P29/Optic_1P29.et"
   m_bMagnified 1
  }
  RK29_AttachmentDef "{AB29C0FFEEB21405}" {
   m_sId "m8541"
   m_sPrefab "{333A794F0B55C019}Prefabs/Weapons/Attachments/Optics/m8541/Optic_M8541.et"
   m_bMagnified 1
  }
  RK29_AttachmentDef "{AB29C0FFEEB22441}" {
   m_sId "mbs"
   m_sPrefab "{6461605F9A86F10C}Prefabs/Weapons/Attachments/Optics/mbs/MBS.et"
   m_bMagnified 1
  }
  RK29_AttachmentDef "{AB29C0FFEEB224A0}" {
   m_sId "pgo7"
   m_sPrefab "{8F83CE66A8F44D72}Prefabs/Weapons/Attachments/Optics/pgo7v3/Optic_PGO7V3.et"
   m_bMagnified 1
  }
  RK29_AttachmentDef "{AB29C0FFEEB21406}" {
   m_sId "ta648mdo"
   m_sPrefab "{A28C985454C90D44}Prefabs/Weapons/Attachments/Optics/ta648mdo/Optic_TA648MDO_base.et"
   m_bMagnified 1
  }
  RK29_AttachmentDef "{AB29C0FFEEB21407}" {
   m_sId "vc18dsco"
   m_sPrefab "{C87346DA8FE13B17}Prefabs/Weapons/Attachments/Optics/vc18dsco/optic_vc18dsco.et"
   m_bMagnified 1
  }
  RK29_AttachmentDef "{AB29C0FFEEB21408}" {
   m_sId "ts30a2"
   m_sPrefab "{5D6774CB06C4B12B}Prefabs/Weapons/Attachments/Optics/ts30a2/optic_ts30a2.et"
   m_bMagnified 1
  }
  RK29_AttachmentDef "{AB29C0FFEEB21409}" {
   m_sId "leupoldmk4"
   m_sPrefab "{ACC9B43941CE5EA6}Prefabs/Weapons/Attachments/Optics/Optic_leupoldMK4/Optic_leupoldMK4.et"
   m_bMagnified 1
  }
  RK29_AttachmentDef "{AB29C0FFEEB2140A}" {
   m_sId "pso1"
   m_sPrefab "{C850A33226B8F9C1}Prefabs/Weapons/Attachments/Optics/Optic_PSO1/Optic_PSO1.et"
   m_bMagnified 1
  }
  RK29_AttachmentDef "{AB29C0FFEEB2140B}" {
   m_sId "1p21"
   m_sPrefab "{695AAA77F84EB238}Prefabs/Weapons/Attachments/Optics/1p21/Optic_1P21.et"
   m_bMagnified 1
  }
 }
}
