SCR_NotificationConfig {
 m_aNotificationDisplayData {
  SCR_NotificationPlayer "{AB29C0FFEE29A101}" {
   m_NotificationKey RK29_LIVE_REKIT
   m_info SCR_UINotificationInfo "{AB29C0FFEE29A102}" {
    Name "%1 swapped loadouts while the round is live"
    Icon "{37204ADEBD67C8A6}UI/Imagesets/Notifications/NotificationIcons.imageset"
    IconSetName "Notification_Loadout"
    m_cNotificationColor NEGATIVE
   }
  }
 }
}
