RK29_SideSetup {
 m_sFactionKey "US"
 m_sBodyPrefab "{284E735C6C70DAD2}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_BaseLoadout.et"
 m_sDefaultKitName "29th Parade"
 m_aClasses {
  RK29_ClassSetup "{AB29C0FFEE290111}" {
   m_sKitName "29th US - Rifleman"
   m_sDisplayName "Rifleman"
   m_sComposition "{AB29C0FFEEB20023}Configs/KitSystem/Kits/US/us_rifleman.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290115}" {
   m_sKitName "29th US - Automatic Rifleman"
   m_sDisplayName "Automatic Rifleman"
   m_sComposition "{AB29C0FFEEB2001F}Configs/KitSystem/Kits/US/us_automatic_rifleman.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE29011A}" {
   m_sKitName "29th US - Light Anti-Tank"
   m_sDisplayName "Anti-Tank"
   m_sComposition "{AB29C0FFEEB20019}Configs/KitSystem/Kits/US/us_anti_tank.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290119}" {
   m_sKitName "29th US - Grenadier"
   m_sDisplayName "Grenadier"
   m_sComposition "{AB29C0FFEEB2001D}Configs/KitSystem/Kits/US/us_grenadier.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290121}" {
   m_sKitName "29th US - Medic"
   m_sDisplayName "Medic"
   m_sComposition "{AB29C0FFEEB20020}Configs/KitSystem/Kits/US/us_medic.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290127}" {
   m_sKitName "29th US - Combat Engineer"
   m_sDisplayName "Combat Engineer"
   m_sComposition "{AB29C0FFEEB2001B}Configs/KitSystem/Kits/US/us_combat_engineer.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290112}" {
   m_sKitName "29th US - Battle Rifle"
   m_sDisplayName "Battle Rifle"
   m_sComposition "{AB29C0FFEEB2001A}Configs/KitSystem/Kits/US/us_battle_rifle.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290125}" {
   m_sKitName "29th US - Sniper"
   m_sDisplayName "Sniper"
   m_sComposition "{AB29C0FFEEB20024}Configs/KitSystem/Kits/US/us_sniper.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE29011F}" {
   m_sKitName "29th US - Squad Leader"
   m_sDisplayName "Leadership"
   m_sComposition "{AB29C0FFEEB2001E}Configs/KitSystem/Kits/US/us_leadership.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE29011B}" {
   m_sKitName "29th US - Crewman"
   m_sDisplayName "Crewman"
   m_sComposition "{AB29C0FFEEB2001C}Configs/KitSystem/Kits/US/us_crewman.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290123}" {
   m_sKitName "29th US - Pilot"
   m_sDisplayName "Pilot"
   m_sComposition "{AB29C0FFEEB20022}Configs/KitSystem/Kits/US/us_pilot.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290143}" {
   m_sKitName "29th Parade"
   m_sDisplayName "Parade"
   m_sComposition "{AB29C0FFEEB20021}Configs/KitSystem/Kits/US/us_parade.conf"
  }
 }
}
