RK29_SideSetup {
 m_sFactionKey "USSR"
 m_sBodyPrefab "{5346CF7E39A65A6B}Prefabs/Characters/Factions/OPFOR/USSR_Army/Character_USSR_Base.et"
 m_sDefaultKitName "29th USSR - Rifleman"
 m_aClasses {
  RK29_ClassSetup "{AB29C0FFEE290113}" {
   m_sKitName "29th USSR - Rifleman"
   m_sDisplayName "Rifleman"
   m_aWeapons {
   }
   m_aOpticCategories {
    "USSR 1x" "USSR Magnified"
   }
   m_sDefaultOptic ""
   m_sComposition "{AB29C0FFEE29B02B}Configs/KitSystem/Kits/USSR/ussr_rifleman.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290116}" {
   m_sKitName "29th USSR - Machine Gunner"
   m_sDisplayName "Machine Gunner"
   m_aWeapons {
   }
   m_aOpticCategories {
    "USSR 1x" "USSR Magnified"
   }
   m_sDefaultOptic ""
   m_sComposition "{AB29C0FFEE29B01C}Configs/KitSystem/Kits/USSR/ussr_machine_gunner.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE29011D}" {
   m_sKitName "29th USSR - Light Anti-Tank"
   m_sDisplayName "Anti-Tank"
   m_aWeapons {
   }
   m_aOpticCategories {
    "USSR 1x" "USSR Magnified"
   }
   m_sDefaultOptic ""
   m_sComposition "{AB29C0FFEE29B025}Configs/KitSystem/Kits/USSR/ussr_anti_tank.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE29011C}" {
   m_sKitName "29th USSR - Grenadier"
   m_sDisplayName "Grenadier"
   m_aWeapons {
   }
   m_aOpticCategories {
    "USSR 1x" "USSR Magnified"
   }
   m_sDefaultOptic ""
   m_sComposition "{AB29C0FFEE29B022}Configs/KitSystem/Kits/USSR/ussr_grenadier.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290122}" {
   m_sKitName "29th USSR - Medic"
   m_sDisplayName "Medic"
   m_aWeapons {
   }
   m_aOpticCategories {
    "USSR 1x" "USSR Magnified"
   }
   m_sDefaultOptic ""
   m_sComposition "{AB29C0FFEE29B035}Configs/KitSystem/Kits/USSR/ussr_medic.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290128}" {
   m_sKitName "29th USSR - Combat Engineer"
   m_sDisplayName "Combat Engineer"
   m_aWeapons {
   }
   m_aOpticCategories {
    "USSR 1x" "USSR Magnified"
   }
   m_sDefaultOptic ""
   m_sComposition "{AB29C0FFEE29B03E}Configs/KitSystem/Kits/USSR/ussr_combat_engineer.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290114}" {
   m_sKitName "29th USSR - Battle Rifle"
   m_sDisplayName "Battle Rifle"
   m_aWeapons {
   }
   m_aOpticCategories {
   }
   m_sDefaultOptic ""
   m_sComposition "{AB29C0FFEE29B02E}Configs/KitSystem/Kits/USSR/ussr_battle_rifle.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290126}" {
   m_sKitName "29th USSR - Sniper"
   m_sDisplayName "Sniper"
   m_aWeapons {
   }
   m_aOpticCategories {
    "USSR Sniper"
   }
   m_sDefaultOptic "{695AAA77F84EB238}Prefabs/Weapons/Attachments/Optics/1p21/Optic_1P21.et"
   m_sComposition "{AB29C0FFEE29B03B}Configs/KitSystem/Kits/USSR/ussr_sniper.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290120}" {
   m_sKitName "29th USSR - Squad Leader"
   m_sDisplayName "Leadership"
   m_aWeapons {
   }
   m_aOpticCategories {
    "USSR 1x" "USSR Magnified"
   }
   m_sDefaultOptic ""
   m_sComposition "{AB29C0FFEE29B031}Configs/KitSystem/Kits/USSR/ussr_leadership.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE29011E}" {
   m_sKitName "29th USSR - Crewman"
   m_sDisplayName "Crewman"
   m_aWeapons {
   }
   m_aOpticCategories {
    "USSR 1x" "USSR Magnified"
   }
   m_sDefaultOptic ""
   m_sComposition "{AB29C0FFEE29B01F}Configs/KitSystem/Kits/USSR/ussr_crewman.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290124}" {
   m_sKitName "29th USSR - Pilot"
   m_sDisplayName "Pilot"
   m_aWeapons {
   }
   m_aOpticCategories {
    "USSR 1x" "USSR Magnified"
   }
   m_sDefaultOptic ""
   m_sComposition "{AB29C0FFEE29B037}Configs/KitSystem/Kits/USSR/ussr_pilot.conf"
  }
 }
}
