RK29_SideSetup {
 m_sFactionKey "US"
 m_aClasses {
  RK29_ClassSetup "{AB29C0FFEE290111}" {
   m_sKitName "29th US - Rifleman"
   m_sDisplayName "Rifleman"
   m_aWeapons {
   }
   m_aOpticCategories {
    "US 1x" "US Magnified"
   }
   m_sDefaultOptic "{08286DDBB1F33FF1}Prefabs/Weapons/Attachments/Optics/Optic_AP2k/Collim_AP2k.et"
   m_sComposition "{AB29C0FFEE29B02A}Configs/KitSystem/Kits/US/us_rifleman.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290115}" {
   m_sKitName "29th US - Automatic Rifleman"
   m_sDisplayName "Machine Gunner"
   m_aWeapons {
   }
   m_aOpticCategories {
    "US 1x" "US Magnified"
   }
   m_sDefaultOptic ""
   m_sComposition "{AB29C0FFEE29B01B}Configs/KitSystem/Kits/US/us_machine_gunner.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE29011A}" {
   m_sKitName "29th US - Light Anti-Tank"
   m_sDisplayName "Combat Engineer"
   m_aWeapons {
   }
   m_aOpticCategories {
    "US 1x" "US Magnified"
   }
   m_sDefaultOptic "{08286DDBB1F33FF1}Prefabs/Weapons/Attachments/Optics/Optic_AP2k/Collim_AP2k.et"
   m_sComposition "{AB29C0FFEE29B024}Configs/KitSystem/Kits/US/us_combat_engineer.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290119}" {
   m_sKitName "29th US - Grenadier"
   m_sDisplayName "Grenadier"
   m_aWeapons {
   }
   m_aOpticCategories {
    "US 1x" "US Magnified"
   }
   m_sDefaultOptic "{08286DDBB1F33FF1}Prefabs/Weapons/Attachments/Optics/Optic_AP2k/Collim_AP2k.et"
   m_sComposition "{AB29C0FFEE29B021}Configs/KitSystem/Kits/US/us_grenadier.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290112}" {
   m_sKitName "29th US - Sniper"
   m_sDisplayName "Sniper"
   m_aWeapons {
   }
   m_aOpticCategories {
    "US Sniper"
   }
   m_sDefaultOptic "{D2018EDB1BBF4C88}Prefabs/Weapons/Attachments/Optics/Optic_ARTII/Optic_ARTII.et"
   m_sComposition "{AB29C0FFEE29B02D}Configs/KitSystem/Kits/US/us_sniper.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE29011F}" {
   m_sKitName "29th US - Squad Leader"
   m_sDisplayName "Squad Leader"
   m_aWeapons {
   }
   m_aOpticCategories {
    "US 1x" "US Magnified"
   }
   m_sDefaultOptic "{08286DDBB1F33FF1}Prefabs/Weapons/Attachments/Optics/Optic_AP2k/Collim_AP2k.et"
   m_sComposition "{AB29C0FFEE29B030}Configs/KitSystem/Kits/US/us_squad_leader.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE29011B}" {
   m_sKitName "29th US - Crewman"
   m_sDisplayName "Crewman"
   m_aWeapons {
   }
   m_aOpticCategories {
    "US 1x" "US Magnified"
   }
   m_sDefaultOptic "{08286DDBB1F33FF1}Prefabs/Weapons/Attachments/Optics/Optic_AP2k/Collim_AP2k.et"
   m_sComposition "{AB29C0FFEE29B01E}Configs/KitSystem/Kits/US/us_crewman.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290143}" {
   m_sKitName "29th Parade"
   m_sDisplayName "Parade"
   m_aWeapons {
   }
   m_aOpticCategories {
   }
   m_sDefaultOptic ""
   m_sComposition "{AB29C0FFEE29B032}Configs/KitSystem/Kits/US/us_parade.conf"
  }
  RK29_ClassSetup "{AB29C0FFEE290141}" {
   m_sKitName "29th US - Current Kit"
   m_sDisplayName "Current Kit"
   m_bLegacyHidden 1
   m_aWeapons {
   }
   m_aOpticCategories {
   }
   m_sDefaultOptic ""
  }
  RK29_ClassSetup "{AB29C0FFEE29C480}" {
   m_sKitName "29th US - Machine Gunner"
   m_sDisplayName "Machine Gunner"
   m_bLegacyHidden 1
   m_aWeapons {
   }
   m_aOpticCategories {
   }
   m_sDefaultOptic ""
  }
 }
}
