GM29_KitLoadoutHolder {
 m_aLoadouts {
  RK29_CurrentKitLoadout "{AB29C0FFEE29A001}" {
   m_sLoadoutName "29th US - Current Kit"
   m_sLoadoutResource "{687483D33CAB3952}Prefabs/Characters/Factions/BLUFOR/29th_US/29th_Character_US_Rifleman.et"
   m_sAffiliatedFaction "US"
  }
  RK29_CurrentKitLoadout "{AB29C0FFEE29A002}" {
   m_sLoadoutName "29th USSR - Current Kit"
   m_sLoadoutResource "{145DBC42B19FC4D6}Prefabs/Characters/Factions/OPFOR/29th_USSR/29th_Character_USSR_Rifleman.et"
   m_sAffiliatedFaction "USSR"
  }
  SCR_FactionPlayerLoadout "{6A26068EC8FB0102}" {
   m_sLoadoutName "29th TP - Recruit"
   m_sLoadoutResource "{9C1B78A6201E8EC5}Prefabs/Characters/Factions/BLUFOR/29th_US_BCT/Character_29th_Recruit_Loadout.et"
   m_sAffiliatedFaction "US"
  }
  SCR_FactionPlayerLoadout "{6A26068EDA4558B6}" {
   m_sLoadoutName "29th TP - Training Staff"
   m_sLoadoutResource "{02890095845CACC3}Prefabs/Characters/Factions/BLUFOR/29th_US_BCT/Character_29th_Training_Staff_Loadout.et"
   m_sAffiliatedFaction "US"
  }
 }
}