ActionManager {
 Actions {
  Action RK29_ToggleKitMenu {
   InputSource InputSourceSum "{AB29C0FFEE294001}" {
    Sources {
     InputSourceValue "{AB29C0FFEE294002}" {
      Input "keyboard:KC_F4"
      Filter InputFilterDown "{AB29C0FFEE294003}" {
      }
     }
    }
   }
  }
  Action RK29_DialogApply {
   InputSource InputSourceSum "{AB29C0FFEE294004}" {
    Sources {
     InputSourceValue "{AB29C0FFEE294005}" {
      Input "keyboard:KC_SPACE"
      Filter InputFilterDown "{AB29C0FFEE294006}" {
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext IngameContext {
   ActionRefs +{
    "RK29_ToggleKitMenu"
   }
  }
  ActionContext CharacterGeneralContext {
   ActionRefs +{
    "RK29_ToggleKitMenu"
   }
  }
  ActionContext DialogContext {
   ActionRefs +{
    "RK29_DialogApply"
   }
  }
 }
}
