SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{AB29C0FFEE294010}" {
   m_sName "rk29"
   m_sDisplayName "Kits - 29th ID"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{AB29C0FFEE294011}" {
     m_sActionName "separator"
     m_sDisplayName "Kits - 29th ID"
    }
    SCR_KeyBindingEntry "{AB29C0FFEE294012}" {
     m_sActionName "RK29_ToggleKitMenu"
     m_sDisplayName "Kit menu"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{AB29C0FFEE294013}" {
     m_sActionName "RK29_DialogApply"
     m_sDisplayName "Apply kit"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{AB29C0FFEE294014}" {
     m_sActionName "RK29_StepFive"
     m_sDisplayName "Count step x5 (hold)"
     m_sPreset "hold"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{AB29C0FFEE294015}" {
     m_sActionName "RK29_StepTen"
     m_sDisplayName "Count step x10 (hold)"
     m_sPreset "hold"
     m_ePrefixType CONTINUOUS
    }
   }
  }
 }
}