RK29_OpticLibrary {
 m_aOpticCategories {
  RK29_OpticCategory "{AB29C0FFEE290101}" {
   m_sName "US 1x"
   m_bMagnified 0
   m_aOptics {
    RK29_OpticOption "{AB29C0FFEE290131}" {
     m_sOpticPrefab "{08286DDBB1F33FF1}Prefabs/Weapons/Attachments/Optics/Optic_AP2k/Collim_AP2k.et"
    }
   }
  }
  RK29_OpticCategory "{AB29C0FFEE290102}" {
   m_sName "US Magnified"
   m_bMagnified 1
   m_aOptics {
    RK29_OpticOption "{AB29C0FFEE290132}" {
     m_sOpticPrefab "{BD496EE1B40DC510}Prefabs/Weapons/Attachments/Optics/Optic_4x20/Optic_4x20.et"
    }
   }
  }
  RK29_OpticCategory "{AB29C0FFEE290105}" {
   m_sName "US Sniper"
   m_bMagnified 1
   m_aOptics {
    RK29_OpticOption "{AB29C0FFEE290136}" {
     m_sOpticPrefab "{D2018EDB1BBF4C88}Prefabs/Weapons/Attachments/Optics/Optic_ARTII/Optic_ARTII.et"
    }
   }
  }
  RK29_OpticCategory "{AB29C0FFEE290103}" {
   m_sName "USSR 1x"
   m_bMagnified 0
   m_aOptics {
    RK29_OpticOption "{AB29C0FFEE290133}" {
     m_sOpticPrefab "{FE2896D202FE7449}Prefabs/Weapons/Attachments/Optics/1p63/Optic_1P63.et"
    }
   }
  }
  RK29_OpticCategory "{AB29C0FFEE290104}" {
   m_sName "USSR Magnified"
   m_bMagnified 1
   m_aOptics {
    RK29_OpticOption "{AB29C0FFEE290134}" {
     m_sOpticPrefab "{8D4BAA235F7EDBEA}Prefabs/Weapons/Attachments/Optics/1p78/Optic_1P78.et"
    }
    RK29_OpticOption "{AB29C0FFEE290135}" {
     m_sOpticPrefab "{ACDF49FACD0701A8}Prefabs/Weapons/Attachments/Optics/Optic_1P29/Optic_1P29.et"
    }
    RK29_OpticOption "{AB29C0FFEE290137}" {
     m_sOpticPrefab "{C850A33226B8F9C1}Prefabs/Weapons/Attachments/Optics/Optic_PSO1/Optic_PSO1.et"
    }
   }
  }
 }
}
