RK29_KitComposition : "{AB29C0FFEE29B026}Configs/KitSystem/Kits/Roles/machine_gunner.conf" {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C0DB}" {
   m_sBlock "{AB29C0FFEE29B100}Configs/KitSystem/Blocks/US/dress.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C21B}" {
   m_sSlot "Vest"
   m_sPrefab "{477A190AF2A17B8A}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_MG.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C21C}" {
   m_sSlot "Back"
   m_sPrefab "{4805E67E2AE30F8D}Prefabs/Items/Equipment/Backpacks/Backpack_Medical_M5.et"
  }
 }
 m_aWeapons +{
  RK29_BlockWeaponEntry "{AB29C0FFEE29C0DC}" {
   m_iSlotIndex 0
   m_sPrefab "{D182DCDD72BF7E34}Prefabs/Weapons/MachineGuns/M60/MG_M60.et"
  }
 }
}
