RK29_KitComposition {
 m_aClothing {
  RK29_BlockClothingEntry "{AB29C0FFEE29C108}" {
   m_sSlot "Hat"
   m_sPrefab "{F545C1BE7C99954A}Prefabs/Characters/HeadGear/Hat_Patrol_US_01/Hat_Patrol_US_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C109}" {
   m_sSlot "Jacket"
   m_sPrefab "{C7861F11D5334C0E}Prefabs/Characters/Uniforms/Jacket_US_BDU.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C10A}" {
   m_sSlot "Pants"
   m_sPrefab "{604BB72BE8E023C2}Prefabs/Characters/Uniforms/Pants_US_BDU.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C10B}" {
   m_sSlot "Boots"
   m_sPrefab "{203EEA924B049EF1}Prefabs/Characters/Footwear/JungleBoots_01/JungleBoots_01.et"
  }
 }
 m_aEquipment {
  RK29_BlockClothingEntry "{AB29C0FFEE29C10C}" {
   m_sSlot "BinocularSlot"
   m_sPrefab "{0CF54B9A85D8E0D4}Prefabs/Items/Equipment/Binoculars/Binoculars_M22/Binoculars_M22.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C10D}" {
   m_sSlot "WristwatchSlot"
   m_sPrefab "{78ED4FEF62BBA728}Prefabs/Items/Equipment/Watches/Watch_SandY184A.et"
  }
 }
 m_aWeapons {
  RK29_BlockWeaponEntry "{AB29C0FFEE29C10E}" {
   m_iSlotIndex 0
   m_sPrefab "{3FB5275A6505B323}Prefabs/Weapons/Rifles/M14/Rifle_M21_base.et"
  }
  RK29_BlockWeaponEntry "{AB29C0FFEE29C10F}" {
   m_iSlotIndex 2
   m_sAlias "handgun"
  }
 }
 m_aItems {
  RK29_BlockItemEntry "{AB29C0FFEE29C110}" {
   m_eSource ALIAS
   m_sAlias "radio"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C111}" {
   m_eSource ALIAS
   m_sAlias "compass"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C112}" {
   m_eSource ALIAS
   m_sAlias "map"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C113}" {
   m_eSource ALIAS
   m_sAlias "bandage"
   m_iCount 2
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C114}" {
   m_eSource ALIAS
   m_sAlias "tourniquet"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C115}" {
   m_eSource ALIAS
   m_sAlias "morphine"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C116}" {
   m_eSource ALIAS
   m_sAlias "flashlight"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C117}" {
   m_sPrefab "{6D18CC33708EE712}Prefabs/Weapons/Magazines/Magazine_762x51_M14_20rnd_Base.et"
   m_iCount 2
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C118}" {
   m_eSource ALIAS
   m_sAlias "frag"
  }
 }
}
