RK29_KitComposition : "{AB29C0FFEE29B029}Configs/KitSystem/Kits/Roles/rifleman.conf" {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C0E4}" {
   m_sBlock "{AB29C0FFEE29B100}Configs/KitSystem/Blocks/US/dress.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C21D}" {
   m_sSlot "Vest"
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_rifleman.et"
  }
 }
 m_aWeapons +{
  RK29_BlockWeaponEntry "{AB29C0FFEE29C0E5}" {
   m_iSlotIndex 0
   m_sPrefab "{A96DAB072888B0A8}Prefabs/Weapons/Rifles/M16/29th_M16A1.et"
  }
 }
}
