RK29_KitComposition : "{AB29C0FFEE29B02C}Configs/KitSystem/Kits/Roles/sniper.conf" {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C0EC}" {
   m_sBlock "{AB29C0FFEE29B100}Configs/KitSystem/Blocks/US/dress.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C21E}" {
   m_sSlot "Hat"
   m_sPrefab "{E12126CDE731EED5}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/Hat_Boonie_US_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C21F}" {
   m_sSlot "Vest"
   m_sPrefab "{9CEA24A1A9CC2675}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_sniper.et"
  }
 }
 m_aWeapons +{
  RK29_BlockWeaponEntry "{AB29C0FFEE29C0ED}" {
   m_iSlotIndex 0
   m_sPrefab "{B31929F65F0D0279}Prefabs/Weapons/Rifles/M14/Rifle_M21.et"
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C0EE}" {
   m_eSource MAG_PRIMARY
   m_sVariant "ap"
   m_iCount 6
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C0EF}" {
   m_eSource ALIAS
   m_sAlias "smoke"
  }
 }
}
