RK29_KitComposition : "{AB29C0FFEE29B02F}Configs/KitSystem/Kits/Roles/squad_leader.conf" {
 m_aBlocks {
  RK29_BlockRef "{AB29C0FFEE29C0F9}" {
   m_sBlock "{AB29C0FFEE29B100}Configs/KitSystem/Blocks/US/dress.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C0FA}" {
   m_sBlock "{AB29C0FFEE29B008}Configs/KitSystem/Blocks/Common/medical_full.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C0FB}" {
   m_sBlock "{AB29C0FFEE29B009}Configs/KitSystem/Blocks/Common/utility_full.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C0FC}" {
   m_sBlock "{AB29C0FFEE29B007}Configs/KitSystem/Blocks/Common/smokes.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C220}" {
   m_sSlot "Vest"
   m_sPrefab "{2E8829632CBA7A9B}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_commander.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C221}" {
   m_sSlot "Back"
   m_sPrefab "{9B6B61BB3FE3DFB0}Prefabs/Items/Equipment/Radios/Radio_ANPRC77.et"
  }
 }
 m_aWeapons +{
  RK29_BlockWeaponEntry "{AB29C0FFEE29C0FD}" {
   m_iSlotIndex 0
   m_sPrefab "{F97A4AC994231900}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine.et"
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C0FE}" {
   m_eSource MAG_PRIMARY
   m_iCount 3
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C0FF}" {
   m_sPrefab "{D41D22DD1B8E921E}Prefabs/Weapons/Grenades/M18/Smoke_M18_Green.et"
   m_iCount 2
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C100}" {
   m_sPrefab "{3343A055A83CB30D}Prefabs/Weapons/Grenades/M18/Smoke_M18_Red.et"
   m_iCount 2
  }
 }
}
