RK29_KitComposition : "{AB29C0FFEE29B01A}Configs/KitSystem/Kits/Roles/role_automatic_rifleman.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA05}" {
  m_Image "{43EA535E240F0B17}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_AR.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C562}" {
   m_sSlot "Vest"
   m_sPrefab "{156DC7109CEE6F69}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_AR.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C458}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C456}" {
     m_sWeapon "m249"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C380}" {
       m_iCount 3
      }
     }
    }
    RK29_WeaponOption "{AB29C0FFEE29C457}" {
     m_sWeapon "m60"
     m_bDefault 1
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C381}" {
       m_iCount 4
      }
     }
    }
   }
  }
 }
}
