RK29_KitComposition : "{AB29C0FFEE29B023}Configs/KitSystem/Kits/Roles/role_anti_tank.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA01}" {
  m_Image "{278C426C1D3B4C27}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_LAT.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C219}" {
   m_sSlot "Vest"
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_rifleman.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C21A}" {
   m_sSlot "Back"
   m_sPrefab "{95D4766BBE46F23D}Prefabs/Items/Equipment/Backpacks/Backpack_IIFS_FieldPack.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C450}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C716}" {
     m_sWeapon "m16a2"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C717}" {
       m_iCount 7
      }
     }
    }
    RK29_WeaponOption "{AB29C0FFEE29C44E}" {
     m_sWeapon "m16a3"
     m_bDefault 1
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C382}" {
       m_iCount 7
      }
     }
    }
   }
  }
  RK29_WeaponSlot "{AB29C0FFEE29C451}" {
   m_iSlot 1
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C44F}" {
     m_sWeapon "m72"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C383}" {
       m_sAlias "rocket"
       m_iCount 3
      }
     }
    }
   }
  }
 }
}
