RK29_KitComposition : "{AB29C0FFEEB20010}Configs/KitSystem/Kits/Roles/role_combat_engineer.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA0C}" {
  m_Image "{8C618068AFC4AC33}UI/Textures/EditorPreviews/Characters/Factions/BLUFOR/US_Army/Character_US_Sapper.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
}
