RK29_KitComposition : "{AB29C0FFEEB20011}Configs/KitSystem/Kits/Roles/role_crewman.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA02}" {
  m_sFaction "US"
  m_Image "{0110ADC89666A310}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_Crew.edds"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
 m_aClothing {
  RK29_ClothingGroup "{AB29C0FFEEB2305E}" {
   m_sId "us_crew_vest"
   m_sDisplayName "Vest"
   m_eKind EXCLUSIVE
   m_sSlot "Vest"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB2305F}" {
     m_sId "alice_rifleman"
     m_bDefault 1
     m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_rifleman.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB2300B}" {
   m_sId "us_crew_hat"
   m_sDisplayName "Helmet"
   m_eKind EXCLUSIVE
   m_sSlot "Hat"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB2300C}" {
     m_sId "hat"
     m_bDefault 1
     m_sPrefab "{C8EAB0985B66824A}Prefabs/Characters/HeadGear/Helmet_DH132_01/Helmet_DH132A_01.et"
    }
    RK29_EntryItem "{AB29C0FFEEB2A1F3}" {
     m_sId "helmet_nvg"
     m_bEnabled 0
     m_sAlias "helmet_nvg"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB2300D}" {
   m_sId "us_crew_jacket"
   m_sDisplayName "Coveralls"
   m_eKind EXCLUSIVE
   m_sSlot "Jacket"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB2300E}" {
     m_sId "jacket"
     m_bDefault 1
     m_sPrefab "{1D99585CF8E34D91}Prefabs/Characters/Uniforms/Suit_Tanker_US_01/Suit_Tanker_US_01.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB2300F}" {
   m_sId "us_crew_pants"
   m_sDisplayName "Trousers"
   m_eKind EXCLUSIVE
   m_sSlot "Pants"
   m_bAllowEmpty 1
  }
  RK29_ClothingGroup "{AB29C0FFEEB23011}" {
   m_sId "us_crew_boots"
   m_sDisplayName "Boots"
   m_eKind EXCLUSIVE
   m_sSlot "Boots"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23012}" {
     m_sId "boots"
     m_bDefault 1
     m_sPrefab "{F05A35BCC44BE9FC}Prefabs/Characters/Footwear/TankerBoots_US_01/TankerBoots_US_01.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23013}" {
   m_sId "us_crew_back"
   m_sDisplayName "Backpack"
   m_eKind EXCLUSIVE
   m_sSlot "Back"
   m_bAllowEmpty 1
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23014}" {
     m_sId "back"
     m_bDefault 1
     m_sPrefab "{9B6B61BB3FE3DFB0}Prefabs/Items/Equipment/Radios/Radio_ANPRC77.et"
    }
   }
   m_aIncludeGroups {
    "back"
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23015}" {
   m_sId "us_crew_handwear"
   m_sDisplayName "Gloves"
   m_eKind EXCLUSIVE
   m_sSlot "HandWear"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23016}" {
     m_sId "handwear"
     m_bDefault 1
     m_sPrefab "{D19C474FA0F42CC4}Prefabs/Characters/Handwear/Gloves_Pilot_US_01/Gloves_Pilot_US_01.et"
    }
   }
  }
 }
}
