RK29_KitComposition : "{AB29C0FFEE29B01D}Configs/KitSystem/Kits/Roles/role_crewman.conf" {
 m_aBlocks {
  RK29_BlockRef "{AB29C0FFEE29C0AD}" {
   m_sBlock "{AB29C0FFEE29B008}Configs/KitSystem/Blocks/Common/medical_full.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C0AE}" {
   m_sBlock "{AB29C0FFEE29B009}Configs/KitSystem/Blocks/Common/utility_full.conf"
  }

 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C20F}" {
   m_sSlot "Hat"
   m_sPrefab "{C8EAB0985B66824A}Prefabs/Characters/HeadGear/Helmet_DH132_01/Helmet_DH132A_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C210}" {
   m_sSlot "Jacket"
   m_sPrefab "{293F577C298061E3}Prefabs/Characters/Uniforms/Jacket_US_BDU_02.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C211}" {
   m_sSlot "Vest"
   m_sPrefab "{F396524995F06BFA}Prefabs/Characters/Vests/Vest_SRU21P/Vest_SRU21P.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C212}" {
   m_sSlot "Pants"
   m_sPrefab "{86BB79B9A2233780}Prefabs/Characters/Uniforms/Pants_US_M65.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C213}" {
   m_sSlot "Boots"
   m_sPrefab "{F05A35BCC44BE9FC}Prefabs/Characters/Footwear/TankerBoots_US_01/TankerBoots_US_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C214}" {
   m_sSlot "Back"
   m_sPrefab "{9B6B61BB3FE3DFB0}Prefabs/Items/Equipment/Radios/Radio_ANPRC77.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C215}" {
   m_sSlot "HandWear"
   m_sPrefab "{D19C474FA0F42CC4}Prefabs/Characters/Handwear/Gloves_Pilot_US_01/Gloves_Pilot_US_01.et"
  }
 }
 m_aEquipment +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C216}" {
   m_sSlot "BinocularSlot"
   m_sPrefab "{0CF54B9A85D8E0D4}Prefabs/Items/Equipment/Binoculars/Binoculars_M22/Binoculars_M22.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C217}" {
   m_sSlot "WristwatchSlot"
   m_sPrefab "{78ED4FEF62BBA728}Prefabs/Items/Equipment/Watches/Watch_SandY184A.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C453}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C452}" {
     m_sWeapon "m16a2_carbine"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3A6}" {
       m_iCount 2
      }
     }
    }
   }
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C408}" {
   m_eSource ALIAS
   m_sAlias "smoke"
   m_iCount 3
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C400}" {
   m_eSource ALIAS
   m_sAlias "frag"
   m_iCount 2
  }
 }
}
