RK29_KitComposition : "{AB29C0FFEEB20012}Configs/KitSystem/Kits/Roles/role_grenadier.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA03}" {
  m_Image "{99D02888988DED59}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_GL.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
}
