RK29_KitComposition : "{AB29C0FFEE29B020}Configs/KitSystem/Kits/Roles/role_grenadier.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA03}" {
  m_Image "{99D02888988DED59}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_GL.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C218}" {
   m_sSlot "Vest"
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_rifleman.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C455}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C454}" {
     m_sWeapon "m16a3_m203"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3A2}" {
       m_iCount 7
      }
      RK29_WeaponAmmo "{AB29C0FFEE29C3C0}" {
       m_sAlias "gl_he"
       m_iCount 7
      }
      RK29_WeaponAmmo "{AB29C0FFEE29C542}" {
       m_sPrefab "{8D0A57DD48B62639}Prefabs/Weapons/Ammo/Ammo_Grenade_Smoke_M715_Green.et"
       m_iCount 2
      }
      RK29_WeaponAmmo "{AB29C0FFEE29C556}" {
       m_sPrefab "{BDD18BEEC1165353}Prefabs/Weapons/Ammo/Ammo_Grenade_Smoke_M713_Red.et"
       m_iCount 2
      }
     }
    }
   }
  }
 }
}
