RK29_KitComposition : "{AB29C0FFEE29B02F}Configs/KitSystem/Kits/Roles/role_leadership.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA04}" {
  m_Image "{E66FEBD3F049BF7D}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_SL.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C220}" {
   m_sSlot "Vest"
   m_sPrefab "{2E8829632CBA7A9B}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_commander.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C221}" {
   m_sSlot "Back"
   m_sPrefab "{9B6B61BB3FE3DFB0}Prefabs/Items/Equipment/Radios/Radio_ANPRC77.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C462}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C461}" {
     m_sWeapon "m16a3"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3A4}" {
       m_iCount 7
      }
     }
    }
   }
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C0FF}" {
   m_sPrefab "{D41D22DD1B8E921E}Prefabs/Weapons/Grenades/M18/Smoke_M18_Green.et"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C100}" {
   m_sPrefab "{3343A055A83CB30D}Prefabs/Weapons/Grenades/M18/Smoke_M18_Red.et"
  }
 }
}
