RK29_KitComposition : "{AB29C0FFEE29B033}Configs/KitSystem/Kits/Roles/role_medic.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA06}" {
  m_Image "{8D3E9B959DCE2B60}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_Medic.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C620}" {
   m_sSlot "Vest"
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_rifleman.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C621}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C622}" {
     m_sWeapon "m16a3"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C623}" {
       m_iCount 7
      }
     }
    }
   }
  }
 }
}
