RK29_KitComposition : "{AB29C0FFEE29B01A}Configs/KitSystem/Kits/Roles/role_machine_gunner.conf" {
 m_aBlocks {
  RK29_BlockRef "{AB29C0FFEE29C09F}" {
   m_sBlock "{AB29C0FFEE29B100}Configs/KitSystem/Blocks/US/us_dress.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C0A0}" {
   m_sBlock "{AB29C0FFEE29B008}Configs/KitSystem/Blocks/Common/medical_full.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C0A1}" {
   m_sBlock "{AB29C0FFEE29B009}Configs/KitSystem/Blocks/Common/utility_full.conf"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C458}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C456}" {
     m_sWeapon "m249"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C380}" {
       m_sAlias "belt"
       m_iCount 3
      }
     }
     m_aBlocks {
      RK29_BlockRef "{AB29C0FFEE29C341}" {
       m_sBlock "{AB29C0FFEE29B113}Configs/KitSystem/Blocks/US/gear_m249.conf"
      }
      RK29_BlockRef "{AB29C0FFEE29C342}" {
       m_sBlock "{AB29C0FFEE29B111}Configs/KitSystem/Blocks/Common/grenades_ar.conf"
      }
     }
    }
    RK29_WeaponOption "{AB29C0FFEE29C457}" {
     m_sWeapon "m60"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C381}" {
       m_sAlias "belt"
       m_iCount 4
      }
     }
     m_aBlocks {
      RK29_BlockRef "{AB29C0FFEE29C344}" {
       m_sBlock "{AB29C0FFEE29B114}Configs/KitSystem/Blocks/US/gear_m60.conf"
      }
      RK29_BlockRef "{AB29C0FFEE29C345}" {
       m_sBlock "{AB29C0FFEE29B112}Configs/KitSystem/Blocks/Common/grenades_mg.conf"
      }
     }
    }
   }
  }
 }
}
