RK29_KitComposition : "{AB29C0FFEEB20016}Configs/KitSystem/Kits/Roles/role_pilot.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA07}" {
  m_Image "{0110ADC89666A310}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_Crew.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
 m_aClothing {
  RK29_ClothingGroup "{AB29C0FFEEB23031}" {
   m_sId "us_pilot_armoredvest"
   m_sDisplayName "Body armour"
   m_eKind EXCLUSIVE
   m_sSlot "ArmoredVest"
   m_bAllowEmpty 1
  }
  RK29_ClothingGroup "{AB29C0FFEEB23032}" {
   m_sId "us_pilot_hat"
   m_sDisplayName "Helmet"
   m_eKind EXCLUSIVE
   m_sSlot "Hat"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23033}" {
     m_sId "hat"
     m_bDefault 1
     m_sPrefab "{483A80042765275F}Prefabs/Characters/HeadGear/Helmet_SPH4_01/Helmet_SPH4_01.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23034}" {
   m_sId "us_pilot_jacket"
   m_sDisplayName "Jacket"
   m_eKind EXCLUSIVE
   m_sSlot "Jacket"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23035}" {
     m_sId "jacket"
     m_bDefault 1
     m_sPrefab "{293F577C298061E3}Prefabs/Characters/Uniforms/Jacket_US_BDU_02.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23036}" {
   m_sId "us_pilot_pants"
   m_sDisplayName "Trousers"
   m_eKind EXCLUSIVE
   m_sSlot "Pants"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23037}" {
     m_sId "pants"
     m_bDefault 1
     m_sPrefab "{86BB79B9A2233780}Prefabs/Characters/Uniforms/Pants_US_M65.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23038}" {
   m_sId "us_pilot_boots"
   m_sDisplayName "Boots"
   m_eKind EXCLUSIVE
   m_sSlot "Boots"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23039}" {
     m_sId "boots"
     m_bDefault 1
     m_sPrefab "{F05A35BCC44BE9FC}Prefabs/Characters/Footwear/TankerBoots_US_01/TankerBoots_US_01.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB2303A}" {
   m_sId "us_pilot_back"
   m_sDisplayName "Backpack"
   m_eKind EXCLUSIVE
   m_sSlot "Back"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB2303B}" {
     m_sId "back"
     m_bDefault 1
     m_sPrefab "{9B6B61BB3FE3DFB0}Prefabs/Items/Equipment/Radios/Radio_ANPRC77.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB2303C}" {
   m_sId "us_pilot_handwear"
   m_sDisplayName "Gloves"
   m_eKind EXCLUSIVE
   m_sSlot "HandWear"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB2303D}" {
     m_sId "handwear"
     m_bDefault 1
     m_sPrefab "{D19C474FA0F42CC4}Prefabs/Characters/Handwear/Gloves_Pilot_US_01/Gloves_Pilot_US_01.et"
    }
   }
  }
 }
}
