RK29_KitComposition : "{AB29C0FFEE29B038}Configs/KitSystem/Kits/Roles/role_pilot.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA07}" {
  m_Image "{0110ADC89666A310}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_Crew.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C650}" {
   m_sSlot "ArmoredVest"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C651}" {
   m_sSlot "Hat"
   m_sPrefab "{483A80042765275F}Prefabs/Characters/HeadGear/Helmet_SPH4_01/Helmet_SPH4_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C652}" {
   m_sSlot "Jacket"
   m_sPrefab "{293F577C298061E3}Prefabs/Characters/Uniforms/Jacket_US_BDU_02.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C653}" {
   m_sSlot "Vest"
   m_sPrefab "{F396524995F06BFA}Prefabs/Characters/Vests/Vest_SRU21P/Vest_SRU21P.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C654}" {
   m_sSlot "Pants"
   m_sPrefab "{86BB79B9A2233780}Prefabs/Characters/Uniforms/Pants_US_M65.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C655}" {
   m_sSlot "Boots"
   m_sPrefab "{F05A35BCC44BE9FC}Prefabs/Characters/Footwear/TankerBoots_US_01/TankerBoots_US_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C656}" {
   m_sSlot "Back"
   m_sPrefab "{9B6B61BB3FE3DFB0}Prefabs/Items/Equipment/Radios/Radio_ANPRC77.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C657}" {
   m_sSlot "HandWear"
   m_sPrefab "{D19C474FA0F42CC4}Prefabs/Characters/Handwear/Gloves_Pilot_US_01/Gloves_Pilot_US_01.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C658}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C659}" {
     m_sWeapon "m16a2_carbine"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C65A}" {
       m_iCount 1
      }
      RK29_WeaponAmmo "{AB29C0FFEE29CB0B}" {
       m_sVariant "tracer"
       m_iCount 2
      }
     }
    }
   }
  }
 }
}
