RK29_KitComposition : "{AB29C0FFEE29B029}Configs/KitSystem/Kits/Roles/role_rifleman.conf" {
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C21D}" {
   m_sSlot "Vest"
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_rifleman.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C45E}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C45D}" {
     m_sWeapon "m16a3"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3A0}" {
       m_iCount 7
      }
     }
    }
   }
  }
 }
}
