RK29_KitComposition : "{AB29C0FFEE29B029}Configs/KitSystem/Kits/Roles/role_rifleman.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA08}" {
  m_Image "{2B0877799B9B6C66}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_Rifleman.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
 m_aWeaponSlots {
  RK29_WeaponSlot "{AB29C0FFEE29C45E}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C710}" {
     m_sWeapon "m16a2"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C711}" {
       m_iCount 9
      }
      RK29_WeaponAmmo "{AB29C0FFEE29CB0D}" {
       m_sVariant "tracer"
       m_iCount 2
      }
     }
    }
    RK29_WeaponOption "{AB29C0FFEE29C45D}" {
     m_sWeapon "m16a3"
     m_bDefault 1
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3A0}" {
       m_iCount 9
      }
      RK29_WeaponAmmo "{AB29C0FFEE29CB0C}" {
       m_sVariant "tracer"
       m_iCount 2
      }
     }
    }
   }
  }
 }
 m_aClothing {
  RK29_BlockClothingEntry "{AB29C0FFEE29C21D}" {
   m_sSlot "Vest"
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_rifleman.et"
  }
 }
}