RK29_KitComposition : "{AB29C0FFEEB20017}Configs/KitSystem/Kits/Roles/role_rifleman.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA08}" {
  m_Image "{2B0877799B9B6C66}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_Rifleman.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
}
