RK29_KitComposition : "{AB29C0FFEE29B039}Configs/KitSystem/Kits/Roles/role_sniper.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA0B}" {
  m_Image "{13AC78F098028758}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_Sniper.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C564}" {
   m_sPrefab "{D41D22DD1B8E921E}Prefabs/Weapons/Grenades/M18/Smoke_M18_Green.et"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C565}" {
   m_sPrefab "{3343A055A83CB30D}Prefabs/Weapons/Grenades/M18/Smoke_M18_Red.et"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C23A}" {
   m_sSlot "Hat"
   m_sPrefab "{E12126CDE731EED5}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/Hat_Boonie_US_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C23B}" {
   m_sSlot "Vest"
   m_sPrefab "{9CEA24A1A9CC2675}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_sniper.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C479}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C47A}" {
     m_sWeapon "m40"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C47B}" {
       m_sAlias "mag"
       m_iCount 7
      }
     }
    }
   }
  }
 }
}
