RK29_KitComposition : "{AB29C0FFEEB20018}Configs/KitSystem/Kits/Roles/role_sniper.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA0B}" {
  m_Image "{13AC78F098028758}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_Sniper.edds"
  m_sFaction "US"
  m_aAuthoredLabels +{
   FACTION_US
  }
 }
 m_aClothing {
  RK29_ClothingGroup "{AB29C0FFEEB2303E}" {
   m_sId "us_sniper_hat"
   m_sDisplayName "Helmet"
   m_eKind EXCLUSIVE
   m_sSlot "Hat"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB2303F}" {
     m_sId "hat"
     m_bDefault 1
     m_sPrefab "{E12126CDE731EED5}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/Hat_Boonie_US_01.et"
    }
   }
  }
 }
}
