RK29_KitComposition : "{AB29C0FFEE29B02C}Configs/KitSystem/Kits/Roles/role_sniper.conf" {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C0EC}" {
   m_sBlock "{AB29C0FFEE29B100}Configs/KitSystem/Blocks/US/us_dress.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C21E}" {
   m_sSlot "Hat"
   m_sPrefab "{E12126CDE731EED5}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/Hat_Boonie_US_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C21F}" {
   m_sSlot "Vest"
   m_sPrefab "{9CEA24A1A9CC2675}Prefabs/Characters/Vests/Vest_ALICE/Variants/29th_Vest_ALICE_sniper.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C460}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C45F}" {
     m_sWeapon "m21"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3A8}" {
       m_sVariant "ap"
       m_iCount 6
      }
     }
    }
   }
  }
 }
 m_aOpticCategories {
  "US Sniper"
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C40C}" {
   m_eSource ALIAS
   m_sAlias "smoke"
   m_iCount 3
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C406}" {
   m_eSource ALIAS
   m_sAlias "frag"
   m_iCount 2
  }
 }
}
