RK29_KitComposition {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C504}" {
   m_sBlock "{AB29C0FFEE29B100}Configs/KitSystem/Blocks/Common/dress.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C013}" {
   m_sBlock "{AB29C0FFEE29B008}Configs/KitSystem/Blocks/Common/medical.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C014}" {
   m_sBlock "{AB29C0FFEE29B009}Configs/KitSystem/Blocks/Common/utility.conf"
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C0E2}" {
   m_eSource ALIAS
   m_sAlias "bayonet"
   m_bOnlyIfPrimaryTakesIt 1
  }
 }
}
