RK29_KitComposition {
 m_aWeapons {
  RK29_WeaponGroupRef "{AB29C0FFEEB23300}" {
   m_sRef "sidearms"
  }
 }
 m_aClothing {
  RK29_ClothingGroupRef "{AB29C0FFEEB23301}" {
   m_sRef "back"
  }
  RK29_ClothingGroupRef "{AB29C0FFEEB23302}" {
   m_sRef "hat"
  }
  RK29_ClothingGroupRef "{AB29C0FFEEB23303}" {
   m_sRef "jacket"
  }
  RK29_ClothingGroupRef "{AB29C0FFEEB23304}" {
   m_sRef "armor"
  }
  RK29_ClothingGroupRef "{AB29C0FFEEB23305}" {
   m_sRef "pants"
  }
  RK29_ClothingGroupRef "{AB29C0FFEEB23306}" {
   m_sRef "boots"
  }
 }
 m_aItems {
  RK29_ItemGroupRef "{AB29C0FFEEB23307}" {
   m_sRef "medical"
  }
  RK29_ItemGroupRef "{AB29C0FFEEB23308}" {
   m_sRef "grenades"
  }
  RK29_ItemGroupRef "{AB29C0FFEEB23309}" {
   m_sRef "utilities"
  }
  RK29_ItemGroupRef "{AB29C0FFEEB2A200}" {
   m_sRef "nightvision"
  }
 }
}
