RK29_KitComposition : "{AB29C0FFEE29B01A}Configs/KitSystem/Kits/Roles/automatic_rifleman.conf" {
 m_aBlocks {
  RK29_BlockRef "{AB29C0FFEE29C0A3}" {
   m_sBlock "{AB29C0FFEE29B101}Configs/KitSystem/Blocks/USSR/dress.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C0A4}" {
   m_sBlock "{AB29C0FFEE29B001}Configs/KitSystem/Blocks/Common/medical_core.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C0A5}" {
   m_sBlock "{AB29C0FFEE29B009}Configs/KitSystem/Blocks/Common/utility_full.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C222}" {
   m_sSlot "Vest"
   m_sPrefab "{4711A4CAF64C4CEE}Prefabs/Characters/Vests/Vest_SovietHarness/Variants/Vest_SovietHarness_AR.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C223}" {
   m_sSlot "Back"
   m_sPrefab "{41A9C55B61F375F0}Prefabs/Items/Equipment/Backpacks/Backpack_Kolobok.et"
  }
 }
 m_aWeapons +{
  RK29_BlockWeaponEntry "{AB29C0FFEE29C0A6}" {
   m_iSlotIndex 0
   m_sPrefab "{A7AF84C6C58BA3E8}Prefabs/Weapons/MachineGuns/RPK74/MG_RPK74.et"
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C0A7}" {
   m_eSource MAG_PRIMARY
   m_iCount 14
  }
 }
}
