RK29_KitComposition : "{AB29C0FFEE29B023}Configs/KitSystem/Kits/Roles/light_antitank.conf" {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C0D2}" {
   m_sBlock "{AB29C0FFEE29B101}Configs/KitSystem/Blocks/USSR/dress.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C22F}" {
   m_sSlot "Vest"
   m_sPrefab "{9713FE6DDCC9510D}Prefabs/Characters/Vests/Vest_Lifchik/Vest_Lifchik.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C230}" {
   m_sSlot "Back"
   m_sPrefab "{6A39B5843B3F36DA}Prefabs/Items/Equipment/Backpacks/Backpack_RPG_Assistant.et"
  }
 }
 m_aWeapons +{
  RK29_BlockWeaponEntry "{AB29C0FFEE29C0D3}" {
   m_iSlotIndex 0
   m_sPrefab "{FA5C25BF66A53DCF}Prefabs/Weapons/Rifles/AK74/Rifle_AK74.et"
  }
  RK29_BlockWeaponEntry "{AB29C0FFEE29C0D4}" {
   m_iSlotIndex 1
   m_sPrefab "{7A82FE978603F137}Prefabs/Weapons/Launchers/RPG7/Launcher_RPG7.et"
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C0D5}" {
   m_sPrefab "{32E12D322E107F1C}Prefabs/Weapons/Ammo/Ammo_Rocket_PG7VM.et"
   m_iCount 3
  }
 }
}
