RK29_KitComposition : "{AB29C0FFEE29B026}Configs/KitSystem/Kits/Roles/machine_gunner.conf" {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C0DD}" {
   m_sBlock "{AB29C0FFEE29B101}Configs/KitSystem/Blocks/USSR/dress.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C231}" {
   m_sSlot "Vest"
   m_sPrefab "{15067AD09803580D}Prefabs/Characters/Vests/Vest_SovietHarness/Variants/Vest_SovietHarness_MG.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C232}" {
   m_sSlot "Back"
   m_sPrefab "{41A9C55B61F375F0}Prefabs/Items/Equipment/Backpacks/Backpack_Kolobok.et"
  }
 }
 m_aWeapons +{
  RK29_BlockWeaponEntry "{AB29C0FFEE29C0DE}" {
   m_iSlotIndex 0
   m_sPrefab "{A89BC9D55FFB4CD8}Prefabs/Weapons/MachineGuns/PKM/MG_PKM.et"
  }
 }
}
