RK29_KitComposition : "{AB29C0FFEE29B029}Configs/KitSystem/Kits/Roles/rifleman.conf" {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C0E6}" {
   m_sBlock "{AB29C0FFEE29B101}Configs/KitSystem/Blocks/USSR/dress.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C233}" {
   m_sSlot "Vest"
   m_sPrefab "{9713FE6DDCC9510D}Prefabs/Characters/Vests/Vest_Lifchik/Vest_Lifchik.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C234}" {
   m_sSlot "Back"
   m_sPrefab "{41A9C55B61F375F0}Prefabs/Items/Equipment/Backpacks/Backpack_Kolobok.et"
  }
 }
 m_aWeapons +{
  RK29_BlockWeaponEntry "{AB29C0FFEE29C0E7}" {
   m_iSlotIndex 0
   m_sPrefab "{96DFD2E7E63B3386}Prefabs/Weapons/Rifles/AK74/Rifle_AK74N.et"
  }
 }
}
