RK29_KitComposition : "{AB29C0FFEE29B02C}Configs/KitSystem/Kits/Roles/sniper.conf" {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C0F0}" {
   m_sBlock "{AB29C0FFEE29B101}Configs/KitSystem/Blocks/USSR/dress.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C235}" {
   m_sSlot "Hat"
   m_sPrefab "{89FD00CB2909667D}Prefabs/Characters/HeadGear/Hat_M88_01/Hat_M88_01_v1_TTsKO.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C236}" {
   m_sSlot "Vest"
   m_sPrefab "{12C8933903D18885}Prefabs/Characters/Vests/Vest_SovietHarness/Variants/Vest_SovietHarness_sharpshooter.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C237}" {
   m_sSlot "Back"
   m_sPrefab "{3DE0155EC9767B98}Prefabs/Items/Equipment/Backpacks/Backpack_Veshmeshok.et"
  }
 }
 m_aWeapons +{
  RK29_BlockWeaponEntry "{AB29C0FFEE29C0F1}" {
   m_iSlotIndex 0
   m_sPrefab "{3EB02CDAD5F23C82}Prefabs/Weapons/Rifles/SVD/Rifle_SVD.et"
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C0F2}" {
   m_eSource MAG_PRIMARY
   m_iCount 4
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C0F3}" {
   m_eSource MAG_PRIMARY
   m_sVariant "lps"
   m_iCount 6
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C0F4}" {
   m_eSource ALIAS
   m_sAlias "frag"
  }
 }
}
