RK29_KitComposition : "{AB29C0FFEE29B02F}Configs/KitSystem/Kits/Roles/squad_leader.conf" {
 m_aBlocks {
  RK29_BlockRef "{AB29C0FFEE29C101}" {
   m_sBlock "{AB29C0FFEE29B101}Configs/KitSystem/Blocks/USSR/dress.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C102}" {
   m_sBlock "{AB29C0FFEE29B008}Configs/KitSystem/Blocks/Common/medical_full.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C103}" {
   m_sBlock "{AB29C0FFEE29B003}Configs/KitSystem/Blocks/Common/utility_core.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C104}" {
   m_sBlock "{AB29C0FFEE29B004}Configs/KitSystem/Blocks/Common/nav_kit.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C105}" {
   m_sBlock "{AB29C0FFEE29B007}Configs/KitSystem/Blocks/Common/smokes.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C238}" {
   m_sSlot "Vest"
   m_sPrefab "{9713FE6DDCC9510D}Prefabs/Characters/Vests/Vest_Lifchik/29th_Vest_Lifchik.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C239}" {
   m_sSlot "Back"
   m_sPrefab "{54C68E438DD34265}Prefabs/Items/Equipment/Radios/Radio_R107M.et"
  }
 }
 m_aWeapons +{
  RK29_BlockWeaponEntry "{AB29C0FFEE29C106}" {
   m_iSlotIndex 0
   m_sPrefab "{96DFD2E7E63B3386}Prefabs/Weapons/Rifles/AK74/Rifle_AK74N.et"
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C107}" {
   m_eSource ALIAS
   m_sAlias "smoke"
  }
 }
}
