RK29_KitComposition : "{AB29C0FFEE29B020}Configs/KitSystem/Kits/Roles/role_grenadier.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA03}" {
  m_Image "{030E2E704B1974C2}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_GL.edds"
  m_sFaction "USSR"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C22D}" {
   m_sSlot "Vest"
   m_sPrefab "{C8516078375CBE45}Prefabs/Characters/Vests/Vest_Lifchik/29th_Vest_Lifchik_GL.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C46A}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C469}" {
     m_sWeapon "ak74n_gp25"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3A3}" {
       m_iCount 5
      }
      RK29_WeaponAmmo "{AB29C0FFEE29CB11}" {
       m_sVariant "tracer"
       m_iCount 2
      }
      RK29_WeaponAmmo "{AB29C0FFEE29C3C1}" {
       m_sAlias "gl_he"
       m_iCount 11
      }
     }
    }
   }
  }
 }
}
