RK29_KitComposition : "{AB29C0FFEE29B038}Configs/KitSystem/Kits/Roles/role_pilot.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA07}" {
  m_Image "{06307450CC54D80E}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_HeliCrew.edds"
  m_sFaction "USSR"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C660}" {
   m_sSlot "Hat"
   m_sPrefab "{EB2F05A3751B905A}Prefabs/Characters/HeadGear/Helmet_TSh4_01/Helmet_TSh4_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C661}" {
   m_sSlot "Jacket"
   m_sPrefab "{78C9B02C0CBD594C}Prefabs/Characters/Uniforms/Jacket_Tanker_USSR_01/Jacket_Tanker_USSR_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C662}" {
   m_sSlot "ArmoredVest"
   m_sPrefab "{506EF3B2F0A69D34}Prefabs/Characters/Vests/Vest_NAZ/Vest_NAZ.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C663}" {
   m_sSlot "Pants"
   m_sPrefab "{DC91A67E1074AAC0}Prefabs/Characters/Uniforms/Pants_Tanker_USSR_01/Pants_Tanker_USSR_01_tucked.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C664}" {
   m_sSlot "Boots"
   m_sPrefab "{C7923961D7235D70}Prefabs/Characters/Footwear/CombatBoots_Soviet_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C665}" {
   m_sSlot "Back"
   m_sPrefab "{54C68E438DD34265}Prefabs/Items/Equipment/Radios/Radio_R107M.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C666}" {
   m_sSlot "HandWear"
   m_sPrefab "{8266820FFDE17477}Prefabs/Characters/Handwear/Gloves_Wool_01/Gloves_Wool_01.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C667}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C668}" {
     m_sWeapon "aks74un"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C669}" {
       m_iCount 3
      }
     }
    }
   }
  }
 }
}
