RK29_KitComposition : "{AB29C0FFEEB2000E}Configs/KitSystem/Kits/Roles/role_anti_tank.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA01}" {
  m_sFaction "USSR"
  m_Image "{7ECA28DD2B20929D}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_LAT.edds"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
}
