RK29_KitComposition : "{AB29C0FFEEB20013}Configs/KitSystem/Kits/Roles/role_leadership.conf" {
 m_aClothing {
  RK29_ClothingGroup "{AB29C0FFEEB2304D}" {
   m_sId "ussr_lead_back"
   m_sDisplayName "Backpack"
   m_eKind EXCLUSIVE
   m_sSlot "Back"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB2304E}" {
     m_sId "back"
     m_bDefault 1
     m_sPrefab "{54C68E438DD34265}Prefabs/Items/Equipment/Radios/Radio_R107M.et"
    }
   }
  }
 }
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA04}" {
  m_Image "{7CB1ED2B23DD26E6}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_SL.edds"
  m_sFaction "USSR"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
 m_aOverrides {
  RK29_Override "{AB29C0FFEEB22107}" {
   m_sId "ussr_lead_grenades"
   m_aAdjust {
    RK29_OverrideAdjust "{AB29C0FFEEB22108}" {
     m_sTarget "grenades/smoke"
     m_iMin 0
     m_iDefault 6
     m_iMax 6
    }
   }
  }
 }
}
