RK29_KitComposition : "{AB29C0FFEE29B023}Configs/KitSystem/Kits/Roles/role_combat_engineer.conf" {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C0D2}" {
   m_sBlock "{AB29C0FFEE29B101}Configs/KitSystem/Blocks/USSR/ussr_dress.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C22F}" {
   m_sSlot "Vest"
   m_sPrefab "{9713FE6DDCC9510D}Prefabs/Characters/Vests/Vest_Lifchik/Vest_Lifchik.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C230}" {
   m_sSlot "Back"
   m_sPrefab "{6A39B5843B3F36DA}Prefabs/Items/Equipment/Backpacks/Backpack_RPG_Assistant.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C465}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C463}" {
     m_sWeapon "ak74n"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C386}" {
       m_iCount 7
      }
     }
    }
   }
  }
  RK29_WeaponSlot "{AB29C0FFEE29C466}" {
   m_iSlot 1
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C464}" {
     m_sWeapon "rpg7"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C387}" {
       m_sAlias "rocket"
       m_iCount 3
      }
     }
    }
   }
  }
 }
}
