RK29_KitComposition : "{AB29C0FFEE29B02F}Configs/KitSystem/Kits/Roles/role_squad_leader.conf" {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C101}" {
   m_sBlock "{AB29C0FFEE29B101}Configs/KitSystem/Blocks/USSR/ussr_dress.conf"
  }


 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C238}" {
   m_sSlot "Vest"
   m_sPrefab "{9713FE6DDCC9510D}Prefabs/Characters/Vests/Vest_Lifchik/29th_Vest_Lifchik.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C239}" {
   m_sSlot "Back"
   m_sPrefab "{54C68E438DD34265}Prefabs/Items/Equipment/Radios/Radio_R107M.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C474}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C472}" {
     m_sWeapon "ak74n"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3A5}" {
       m_iCount 4
      }
     }
    }
   }
  }
  RK29_WeaponSlot "{AB29C0FFEE29C475}" {
   m_iSlot 2
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C473}" {
     m_sWeapon "sidearm"
    }
   }
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C3F1}" {
   m_eSource ALIAS
   m_sAlias "nav"
  }
 }
}
