RK29_KitComposition : "{AB29C0FFEEB20011}Configs/KitSystem/Kits/Roles/role_crewman.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA02}" {
  m_sFaction "USSR"
  m_Image "{89CC22613875F3F7}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/KLMK/Character_USSR_SR_KLMK.edds"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
 m_aClothing {
  RK29_ClothingGroup "{AB29C0FFEEB23040}" {
   m_sId "ussr_crew_hat"
   m_sDisplayName "Helmet"
   m_eKind EXCLUSIVE
   m_sSlot "Hat"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23041}" {
     m_sId "hat"
     m_bDefault 1
     m_sPrefab "{EB2F05A3751B905A}Prefabs/Characters/HeadGear/Helmet_TSh4_01/Helmet_TSh4_01.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23042}" {
   m_sId "ussr_crew_jacket"
   m_sDisplayName "Jacket"
   m_eKind EXCLUSIVE
   m_sSlot "Jacket"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23043}" {
     m_sId "jacket"
     m_bDefault 1
     m_sPrefab "{78C9B02C0CBD594C}Prefabs/Characters/Uniforms/Jacket_Tanker_USSR_01/Jacket_Tanker_USSR_01.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23044}" {
   m_sId "ussr_crew_armoredvest"
   m_sDisplayName "Body armour"
   m_eKind EXCLUSIVE
   m_sSlot "ArmoredVest"
   m_bAllowEmpty 1
  }
  RK29_ClothingGroup "{AB29C0FFEEB23045}" {
   m_sId "ussr_crew_pants"
   m_sDisplayName "Trousers"
   m_eKind EXCLUSIVE
   m_sSlot "Pants"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23046}" {
     m_sId "pants"
     m_bDefault 1
     m_sPrefab "{DC91A67E1074AAC0}Prefabs/Characters/Uniforms/Pants_Tanker_USSR_01/Pants_Tanker_USSR_01_tucked.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23047}" {
   m_sId "ussr_crew_boots"
   m_sDisplayName "Boots"
   m_eKind EXCLUSIVE
   m_sSlot "Boots"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23048}" {
     m_sId "boots"
     m_bDefault 1
     m_sPrefab "{C7923961D7235D70}Prefabs/Characters/Footwear/CombatBoots_Soviet_01.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23049}" {
   m_sId "ussr_crew_back"
   m_sDisplayName "Backpack"
   m_eKind EXCLUSIVE
   m_sSlot "Back"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB2304A}" {
     m_sId "back"
     m_bDefault 1
     m_sPrefab "{54C68E438DD34265}Prefabs/Items/Equipment/Radios/Radio_R107M.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB2304B}" {
   m_sId "ussr_crew_handwear"
   m_sDisplayName "Gloves"
   m_eKind EXCLUSIVE
   m_sSlot "HandWear"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB2304C}" {
     m_sId "handwear"
     m_bDefault 1
     m_sPrefab "{8266820FFDE17477}Prefabs/Characters/Handwear/Gloves_Wool_01/Gloves_Wool_01.et"
    }
   }
  }
 }
}
