RK29_KitComposition : "{AB29C0FFEE29B01A}Configs/KitSystem/Kits/Roles/role_machine_gunner.conf" {
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C46D}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C46B}" {
     m_sWeapon "rpk74n"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C384}" {
       m_iCount 17
      }
     }
     m_aBlocks {
      RK29_BlockRef "{AB29C0FFEE29C34B}" {
       m_sBlock "{AB29C0FFEE29B115}Configs/KitSystem/Blocks/USSR/gear_rpk.conf"
      }
     }
    }
    RK29_WeaponOption "{AB29C0FFEE29C46C}" {
     m_sWeapon "pkmn"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C385}" {
       m_iCount 4
      }
     }
     m_aBlocks {
      RK29_BlockRef "{AB29C0FFEE29C34E}" {
       m_sBlock "{AB29C0FFEE29B116}Configs/KitSystem/Blocks/USSR/gear_pkm.conf"
      }
     }
    }
   }
  }
 }
}
