RK29_KitComposition : "{AB29C0FFEEB20017}Configs/KitSystem/Kits/Roles/role_rifleman.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA08}" {
  m_Image "{6A8FF7A3F9007CD0}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_Rifleman.edds"
  m_sFaction "USSR"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
}
