RK29_KitComposition : "{AB29C0FFEEB20010}Configs/KitSystem/Kits/Roles/role_combat_engineer.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA0C}" {
  m_Image "{BD1C0EB9EEE10B25}UI/Textures/EditorPreviews/Characters/Factions/OPFOR/USSR_Army/Character_USSR_Sapper.edds"
  m_sFaction "USSR"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
}
