RK29_KitComposition : "{AB29C0FFEE29B020}Configs/KitSystem/Kits/Roles/role_grenadier.conf" {
 m_aBlocks +{
  RK29_BlockRef "{AB29C0FFEE29C0C3}" {
   m_sBlock "{AB29C0FFEE29B101}Configs/KitSystem/Blocks/USSR/ussr_dress.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C22D}" {
   m_sSlot "Vest"
   m_sPrefab "{C8516078375CBE45}Prefabs/Characters/Vests/Vest_Lifchik/Vest_Lifchik_GL.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C22E}" {
   m_sSlot "Back"
   m_sPrefab "{41A9C55B61F375F0}Prefabs/Items/Equipment/Backpacks/Backpack_Kolobok.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C46A}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C469}" {
     m_sWeapon "ak74n_gp25"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3A3}" {
       m_iCount 8
      }
      RK29_WeaponAmmo "{AB29C0FFEE29C3C1}" {
       m_sAlias "gl_he"
       m_iCount 11
      }
     }
    }
   }
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C40E}" {
   m_eSource ALIAS
   m_sAlias "smoke"
   m_iCount 2
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C405}" {
   m_eSource ALIAS
   m_sAlias "frag"
   m_iCount 7
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C0C6}" {
   m_eSource ALIAS
   m_sAlias "flare"
   m_iCount 2
  }
 }
}
