RK29_KitComposition : "{AB29C0FFEEB20018}Configs/KitSystem/Kits/Roles/role_sniper.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA0B}" {
  m_Image "{CA21F66986FE4498}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_Sharpshooter.edds"
  m_sFaction "USSR"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
 m_aClothing {
  RK29_ClothingGroup "{AB29C0FFEEB2305C}" {
   m_sId "ussr_sniper_hat"
   m_sDisplayName "Helmet"
   m_eKind EXCLUSIVE
   m_sSlot "Hat"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB2305D}" {
     m_sId "hat"
     m_bDefault 1
     m_sPrefab "{89FD00CB2909667D}Prefabs/Characters/HeadGear/Hat_M88_01/Hat_M88_01_v1_TTsKO.et"
    }
   }
  }
 }
 m_aOverrides {
  RK29_Override "{AB29C0FFEEB22109}" {
   m_sId "ussr_sniper_grenades"
   m_aAdjust {
    RK29_OverrideAdjust "{AB29C0FFEEB2210A}" {
     m_sTarget "grenades/smoke"
     m_iMin 0
     m_iDefault 4
     m_iMax 4
    }
   }
  }
  RK29_Override "{AB29C0FFEEB22E42}" {
   m_sId "sniper_pack"
   m_aAdjust {
    RK29_OverrideAdjust "{AB29C0FFEEB22E41}" {
     m_sTarget "back/veshmeshok"
     m_bDefault 1
    }
   }
  }
 }
}
