RK29_KitComposition : "{AB29C0FFEEB20015}Configs/KitSystem/Kits/Roles/role_medic.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA06}" {
  m_Image "{9225D8E3CFAD7926}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_Medic.edds"
  m_sFaction "USSR"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
 m_aOverrides {
  RK29_Override "{AB29C0FFEEB22E3E}" {
   m_sId "medic_pack"
   m_aAdjust {
    RK29_OverrideAdjust "{AB29C0FFEEB22E3D}" {
     m_sTarget "back_medic/medical_sov"
     m_bDefault 1
    }
   }
  }
 }
}
