RK29_KitComposition : "{AB29C0FFEE29B01D}Configs/KitSystem/Kits/Roles/role_crewman.conf" {
 m_aBlocks {
  RK29_BlockRef "{AB29C0FFEE29C0B5}" {
   m_sBlock "{AB29C0FFEE29B008}Configs/KitSystem/Blocks/Common/medical_full.conf"
  }
  RK29_BlockRef "{AB29C0FFEE29C0B6}" {
   m_sBlock "{AB29C0FFEE29B003}Configs/KitSystem/Blocks/Common/utility_core.conf"
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C224}" {
   m_sSlot "Hat"
   m_sPrefab "{EB2F05A3751B905A}Prefabs/Characters/HeadGear/Helmet_TSh4_01/Helmet_TSh4_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C225}" {
   m_sSlot "Jacket"
   m_sPrefab "{78C9B02C0CBD594C}Prefabs/Characters/Uniforms/Jacket_Tanker_USSR_01/Jacket_Tanker_USSR_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C226}" {
   m_sSlot "ArmoredVest"
   m_sPrefab "{506EF3B2F0A69D34}Prefabs/Characters/Vests/Vest_NAZ/Vest_NAZ.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C227}" {
   m_sSlot "Pants"
   m_sPrefab "{DC91A67E1074AAC0}Prefabs/Characters/Uniforms/Pants_Tanker_USSR_01/Pants_Tanker_USSR_01_tucked.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C228}" {
   m_sSlot "Boots"
   m_sPrefab "{C7923961D7235D70}Prefabs/Characters/Footwear/CombatBoots_Soviet_01.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C229}" {
   m_sSlot "Back"
   m_sPrefab "{54C68E438DD34265}Prefabs/Items/Equipment/Radios/Radio_R107M.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C22A}" {
   m_sSlot "HandWear"
   m_sPrefab "{8266820FFDE17477}Prefabs/Characters/Handwear/Gloves_Wool_01/Gloves_Wool_01.et"
  }
 }
 m_aEquipment +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C22B}" {
   m_sSlot "BinocularSlot"
   m_sPrefab "{243948B23D90BECB}Prefabs/Items/Equipment/Binoculars/Binoculars_B8/Binoculars_B8.et"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C22C}" {
   m_sSlot "WristwatchSlot"
   m_sPrefab "{6FD6C96121905202}Prefabs/Items/Equipment/Watches/Watch_Vostok.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C468}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C467}" {
     m_sWeapon "aks74un"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3A7}" {
       m_iCount 1
      }
     }
    }
   }
  }
 }
 m_aItems +{
  RK29_BlockItemEntry "{AB29C0FFEE29C401}" {
   m_eSource ALIAS
   m_sAlias "frag"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C3F0}" {
   m_eSource ALIAS
   m_sAlias "nav"
  }
 }
}
