RK29_KitComposition : "{AB29C0FFEE29B029}Configs/KitSystem/Kits/Roles/role_rifleman.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA08}" {
  m_Image "{6A8FF7A3F9007CD0}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_Rifleman.edds"
  m_sFaction "USSR"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
 m_aWeaponSlots {
  RK29_WeaponSlot "{AB29C0FFEE29C46F}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C46E}" {
     m_sWeapon "ak74n"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C3A1}" {
       m_iCount 11
      }
     }
    }
   }
  }
 }
 m_aClothing {
  RK29_BlockClothingEntry "{AB29C0FFEE29C233}" {
   m_sSlot "Vest"
   m_sPrefab "{9713FE6DDCC9510D}Prefabs/Characters/Vests/Vest_Lifchik/29th_Vest_Lifchik.et"
  }
 }
}