RK29_KitComposition : "{AB29C0FFEEB20016}Configs/KitSystem/Kits/Roles/role_pilot.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA07}" {
  m_Image "{06307450CC54D80E}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_HeliCrew.edds"
  m_sFaction "USSR"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
 m_aClothing {
  RK29_ClothingGroup "{AB29C0FFEEB2304F}" {
   m_sId "ussr_pilot_hat"
   m_sDisplayName "Helmet"
   m_eKind EXCLUSIVE
   m_sSlot "Hat"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23050}" {
     m_sId "hat"
     m_bDefault 1
     m_sPrefab "{E49D9EE7E2B3016C}Prefabs/Characters/HeadGear/Helmet_ZSh5_01/Helmet_ZSh5_01.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23051}" {
   m_sId "ussr_pilot_jacket"
   m_sDisplayName "Jacket"
   m_eKind EXCLUSIVE
   m_sSlot "Jacket"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23052}" {
     m_sId "jacket"
     m_bDefault 1
     m_sPrefab "{6835DAF42A09E23C}Prefabs/Characters/Uniforms/Jacket_Pilot_USSR_01/Jacket_Pilot_USSR_01.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23053}" {
   m_sId "ussr_pilot_armoredvest"
   m_sDisplayName "Body armour"
   m_eKind EXCLUSIVE
   m_sSlot "ArmoredVest"
   m_bAllowEmpty 1
  }
  RK29_ClothingGroup "{AB29C0FFEEB23054}" {
   m_sId "ussr_pilot_pants"
   m_sDisplayName "Trousers"
   m_eKind EXCLUSIVE
   m_sSlot "Pants"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23055}" {
     m_sId "pants"
     m_bDefault 1
     m_sPrefab "{6B7F32F1F8A191B0}Prefabs/Characters/Uniforms/Pants_Pilot_USSR_01/Pants_Pilot_USSR_01_tucked.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23056}" {
   m_sId "ussr_pilot_boots"
   m_sDisplayName "Boots"
   m_eKind EXCLUSIVE
   m_sSlot "Boots"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23057}" {
     m_sId "boots"
     m_bDefault 1
     m_sPrefab "{C7923961D7235D70}Prefabs/Characters/Footwear/CombatBoots_Soviet_01.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB23058}" {
   m_sId "ussr_pilot_back"
   m_sDisplayName "Backpack"
   m_eKind EXCLUSIVE
   m_sSlot "Back"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB23059}" {
     m_sId "back"
     m_bDefault 1
     m_sPrefab "{54C68E438DD34265}Prefabs/Items/Equipment/Radios/Radio_R107M.et"
    }
   }
  }
  RK29_ClothingGroup "{AB29C0FFEEB2305A}" {
   m_sId "ussr_pilot_handwear"
   m_sDisplayName "Gloves"
   m_eKind EXCLUSIVE
   m_sSlot "HandWear"
   m_aEntries {
    RK29_EntryItem "{AB29C0FFEEB2305B}" {
     m_sId "handwear"
     m_bDefault 1
     m_sPrefab "{8266820FFDE17477}Prefabs/Characters/Handwear/Gloves_Wool_01/Gloves_Wool_01.et"
    }
   }
  }
 }
}
