RK29_KitComposition : "{AB29C0FFEE29B033}Configs/KitSystem/Kits/Roles/role_medic.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA06}" {
  m_Image "{9225D8E3CFAD7926}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_Medic.edds"
  m_sFaction "USSR"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
 m_aClothing +{
  RK29_BlockClothingEntry "{AB29C0FFEE29C630}" {
   m_sSlot "Vest"
   m_sPrefab "{9713FE6DDCC9510D}Prefabs/Characters/Vests/Vest_Lifchik/Vest_Lifchik.et"
  }
 }
 m_aWeaponSlots +{
  RK29_WeaponSlot "{AB29C0FFEE29C631}" {
   m_aOptions {
    RK29_WeaponOption "{AB29C0FFEE29C632}" {
     m_sWeapon "ak74n"
     m_aAmmo {
      RK29_WeaponAmmo "{AB29C0FFEE29C633}" {
       m_iCount 7
      }
     }
    }
   }
  }
 }
}
