RK29_KitComposition : "{AB29C0FFEEB2000F}Configs/KitSystem/Kits/Roles/role_battle_rifle.conf" {
 m_UIInfo SCR_EditableEntityUIInfo "{AB29C0FFEE29CA09}" {
  m_Image "{CA21F66986FE4498}UI/Textures/EditorPreviews/Characters/OPFOR/USSR_Army/Character_USSR_Sharpshooter.edds"
  m_sFaction "USSR"
  m_aAuthoredLabels +{
   FACTION_USSR
  }
 }
 m_aOverrides {
  RK29_Override "{AB29C0FFEEB22E40}" {
   m_sId "br_pack"
   m_aAdjust {
    RK29_OverrideAdjust "{AB29C0FFEEB22E3F}" {
     m_sTarget "back/veshmeshok"
     m_bDefault 1
    }
   }
  }
 }
}
