RK29_KitSetup {
 m_bNoTimerOpen 0
 m_bVerboseLogging 0
 m_aSideConfigs {
  "{AB29C0FFEEB20031}Configs/KitSystem/Rosters/RK29_Roster_US.conf"
  "{AB29C0FFEEB20032}Configs/KitSystem/Rosters/RK29_Roster_USSR.conf"
 }
 m_aAliasConfigs {
  "{AB29C0FFEEB20008}Configs/KitSystem/Catalogs/RK29_Aliases.conf"
 }
 m_aMagSetConfigs {
  "{AB29C0FFEEB20009}Configs/KitSystem/Catalogs/RK29_Magazines.conf"
 }
 m_aWeaponConfigs {
  "{AB29C0FFEEB2000C}Configs/KitSystem/Catalogs/RK29_Weapons.conf"
 }
 m_aChoiceConfigs {
  "{AB29C0FFEEB21000}Configs/KitSystem/Catalogs/RK29_Choices.conf"
 }
 m_aAttachmentConfigs {
  "{AB29C0FFEEB21040}Configs/KitSystem/Catalogs/RK29_Attachments.conf"
 }
 m_aOverrideConfigs {
  "{AB29C0FFEEB22F17}Configs/KitSystem/Catalogs/RK29_Overrides.conf"
 }
}
