RK29_KitSetup {
 m_bNoTimerOpen 0
 m_bVerboseLogging 0
 m_aSideConfigs {
  "{AB29C0FFEE297001}Configs/KitSystem/Rosters/RK29_Roster_US.conf"
  "{AB29C0FFEE297002}Configs/KitSystem/Rosters/RK29_Roster_USSR.conf"
 }
 m_aOpticConfigs {
  "{AB29C0FFEE297003}Configs/KitSystem/Catalogs/RK29_Optics.conf"
 }
 m_aAliasConfigs {
  "{AB29C0FFEE297004}Configs/KitSystem/Catalogs/RK29_Aliases.conf"
 }
 m_aMagSetConfigs {
  "{AB29C0FFEE297005}Configs/KitSystem/Catalogs/RK29_Magazines.conf"
 }
 m_aSquadConfigs {
  "{AB29C0FFEE297006}Configs/KitSystem/Catalogs/RK29_Squads.conf"
 }
}
