GM29_GroupPresetHolder {
 m_aGroupPresets {
  SCR_GroupRolePresetConfig "{7A29D1440C915B01}" {
   m_sGroupName "29th HQ"
   m_sGroupDescription "Command and support element."
   m_iGroupSize 5
   m_sGroupRoleName "HQ"
   m_eGroupRole 0
   m_aLoadoutResources {
    "{2E1382EE0385F9C8}Prefabs/Characters/Factions/BLUFOR/29th_US/29th_Character_US_SL.et"
    "{A8507C7BBAF64A71}Prefabs/Characters/Factions/OPFOR/29th_USSR/29th_Character_USSR_SL.et"
    "{4F76AB23D73DC677}Prefabs/Characters/Factions/BLUFOR/29th_US/29th_Character_US_Sniper.et"
    "{B056E800F6286831}Prefabs/Characters/Factions/OPFOR/29th_USSR/29TH_Character_USSR_Sharpshooter.et"
    "{894628A45793E7A0}Prefabs/Characters/Factions/BLUFOR/29th_US_Parade/Character_29th_Parade_Loadout.et"
   }
  }
  SCR_GroupRolePresetConfig "{7A29D1440C915B02}" {
   m_sGroupName "29th Squad"
   m_sGroupDescription "Standard infantry squad."
   m_iGroupSize 12
   m_sGroupRoleName "Squad"
   m_eGroupRole 1
   m_aLoadoutResources {
    "{2E1382EE0385F9C8}Prefabs/Characters/Factions/BLUFOR/29th_US/29th_Character_US_SL.et"
    "{687483D33CAB3952}Prefabs/Characters/Factions/BLUFOR/29th_US/29th_Character_US_Rifleman.et"
    "{FFA72F3D20D51293}Prefabs/Characters/Factions/BLUFOR/29th_US/29th_Character_US_AR.et"
    "{118CADEB5F4E4F38}Prefabs/Characters/Factions/BLUFOR/29th_US/29th_Character_US_MG.et"
    "{4E4E0DD0C6B632F1}Prefabs/Characters/Factions/BLUFOR/29th_US/29th_Character_US_GL.et"
    "{505B0F46348BC94C}Prefabs/Characters/Factions/BLUFOR/29th_US/29th_Character_US_LAT.et"
    "{4F76AB23D73DC677}Prefabs/Characters/Factions/BLUFOR/29th_US/29th_Character_US_Sniper.et"
    "{A8507C7BBAF64A71}Prefabs/Characters/Factions/OPFOR/29th_USSR/29th_Character_USSR_SL.et"
    "{145DBC42B19FC4D6}Prefabs/Characters/Factions/OPFOR/29th_USSR/29th_Character_USSR_Rifleman.et"
    "{862E3B66D0316F0A}Prefabs/Characters/Factions/OPFOR/29th_USSR/29th_Character_USSR_AR.et"
    "{8A60AEBD529FEB8B}Prefabs/Characters/Factions/OPFOR/29th_USSR/29th_Character_USSR_MG.et"
    "{6B00D3FC285E0AE0}Prefabs/Characters/Factions/OPFOR/29th_USSR/29th_Character_USSR_GL.et"
    "{9833B84F57F9F22F}Prefabs/Characters/Factions/OPFOR/29th_USSR/29TH_Character_USSR_LAT.et"
    "{B056E800F6286831}Prefabs/Characters/Factions/OPFOR/29th_USSR/29TH_Character_USSR_Sharpshooter.et"
    "{894628A45793E7A0}Prefabs/Characters/Factions/BLUFOR/29th_US_Parade/Character_29th_Parade_Loadout.et"
   }
  }
  SCR_GroupRolePresetConfig "{7A29D1440C915B03}" {
   m_sGroupName "29th Crew"
   m_sGroupDescription "Vehicle crew element."
   m_iGroupSize 3
   m_sGroupRoleName "Crew"
   m_eGroupRole 2
   m_aLoadoutResources {
    "{5C0BCD473FB7ED03}Prefabs/Characters/Factions/BLUFOR/29th_US/29th_Character_US_Crew.et"
    "{8A88472E69F0E77F}Prefabs/Characters/Factions/OPFOR/29th_USSR/29th_Character_USSR_Crew.et"
   }
  }
 }
}
