RK29_KitBlock {
 m_aClothing {
  RK29_BlockClothingEntry "{AB29C0FFEE29C200}" {
   m_sSlot "Hat"
   m_sAlias "helmet"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C201}" {
   m_sSlot "Jacket"
   m_sAlias "jacket"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C202}" {
   m_sSlot "ArmoredVest"
   m_sAlias "armor"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C203}" {
   m_sSlot "Pants"
   m_sAlias "pants"
  }
  RK29_BlockClothingEntry "{AB29C0FFEE29C204}" {
   m_sSlot "Boots"
   m_sAlias "boots"
  }
 }
}
