RK29_KitBlock {
 m_aItems {
  RK29_BlockItemEntry "{AB29C0FFEE29C310}" {
   m_eSource ALIAS
   m_sAlias "frag"
   m_iCount 4
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C311}" {
   m_eSource ALIAS
   m_sAlias "smoke"
   m_iCount 2
  }
 }
}
