RK29_KitBlock {
 m_aItems {
  RK29_BlockItemEntry "{AB29C0FFEE29C007}" {
   m_eSource ALIAS
   m_sAlias "map"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C008}" {
   m_eSource ALIAS
   m_sAlias "compass"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C009}" {
   m_eSource ALIAS
   m_sAlias "flashlight"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C00A}" {
   m_eSource ALIAS
   m_sAlias "radio"
  }
 }
}
