RK29_KitBlock {
 m_aItems {
  RK29_BlockItemEntry "{AB29C0FFEE29C3E0}" {
   m_eSource ALIAS
   m_sAlias "map"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C3E1}" {
   m_eSource ALIAS
   m_sAlias "compass"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C3E2}" {
   m_eSource ALIAS
   m_sAlias "flashlight"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C3E3}" {
   m_eSource ALIAS
   m_sAlias "radio"
  }
 }
}
