RK29_KitBlock {
 m_aItems {
  RK29_BlockItemEntry "{AB29C0FFEE29C3E4}" {
   m_eSource ALIAS
   m_sAlias "map"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C3E5}" {
   m_eSource ALIAS
   m_sAlias "compass"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C3E6}" {
   m_eSource ALIAS
   m_sAlias "flashlight"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C3E7}" {
   m_eSource ALIAS
   m_sAlias "radio"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C3E8}" {
   m_eSource ALIAS
   m_sAlias "nav"
  }
  RK29_BlockItemEntry "{AB29C0FFEE29C3E9}" {
   m_eSource ALIAS
   m_sAlias "etool"
  }
 }
}
